export enum GpsNatives {
  CreateMapNode,
  DestroyMapNode,
  IsValidMapNode,
  GetMapNodePos,
  CreateConnection,
  DestroyConnection,
  GetConnectionSource,
  GetConnectionTarget,
  GetHighestMapNodeID,
  GetRandomMapNode,
  GetMapNodeConnectionCount,
  GetMapNodeConnection,
  GetConnectionBetweenMapNodes,
  GetDistanceBetweenMapNodes,
  GetMapNodeDistanceFromPoint,
  GetAngleBetweenMapNodes,
  GetMapNodeAngleFromPoint,
  GetClosestMapNodeToPoint,
  SaveMapNodesToFile,
  FindPath,
  FindPathThreaded,
  IsValidPath,
  GetPathSize,
  GetPathLength,
  GetPathNode,
  GetPathNodeIndex,
  DestroyPath,
}

export enum GpsError {
  None = 0,
  InvalidParams = -1,
  InvalidPath = -2,
  InvalidNode = -3,
  InvalidConnection = -4,
  Internal = -5,
}
