export enum StreamerDistances {
  OBJECT_SD = 300.0,
  OBJECT_DD = 0.0,
  PICKUP_SD = 200.0,
  CP_SD = PICKUP_SD,
  RACE_CP_SD = PICKUP_SD,
  MAP_ICON_SD = PICKUP_SD,
  TEXT_3D_LABEL_SD = PICKUP_SD,
  ACTOR_SD = PICKUP_SD,
}
