export enum InvalidEnum {
  NO_TEAM = 255,
  INVALID_PLAYER_ID = 0xffff,
  INVALID_VEHICLE_ID = 0xffff,
  INVALID_ACTOR_ID = 0xffff,
  INVALID_OBJECT_ID = 0xffff,
  INVALID_MENU = 0xff,
  INVALID_TEXT_DRAW = 0xffff,
  INVALID_PLAYER_TEXT_DRAW = 0xffff,
  INVALID_GANG_ZONE = -1,
  INVALID_3DTEXT_ID = 0xffff,
  INVALID_PLAYER_3DTEXT_ID = 0xffff,
}
