export enum InvalidEnum {
  NO_TEAM = 255,
  PLAYER_ID = 0xffff,
  VEHICLE_ID = PLAYER_ID,
  ACTOR_ID = PLAYER_ID,
  OBJECT_ID = PLAYER_ID,
  MENU = -1,
  TEXT_DRAW = PLAYER_ID,
  PLAYER_TEXT_DRAW = PLAYER_ID,
  GANG_ZONE = -1,
  _3DTEXT_ID = PLAYER_ID,
  PLAYER_3DTEXT_ID = PLAYER_ID,
}
