export enum ConnectionStatusEnum {
  NO_ACTION,
  DISCONNECT_ASAP,
  DISCONNECT_ASAP_SILENTLY,
  DISCONNECT_ON_NO_ACK,
  REQUESTED_CONNECTION,
  HANDLING_CONNECTION_REQUEST,
  UNVERIFIED_SENDER,
  SET_ENCRYPTION_ON_MULTIPLE_16_BYTE_PACKET,
  CONNECTED,
}
