import type { IAnimateInfo } from "core/interfaces";

export const animateLib = new Map<string, Array<IAnimateInfo>>([
  ["AIRPORT", [{ n: "thrw_barl_thrw", d: 2.0 }]],
  [
    "Attractors",
    [
      { n: "Stepsit_in", d: 1.67 },
      { n: "Stepsit_loop", d: 3.33 },
      { n: "Stepsit_out", d: 1.67 },
    ],
  ],
  [
    "BAR",
    [
      { n: "Barcustom_get", d: 3.0 },
      { n: "Barcustom_loop", d: 2.0 },
      { n: "Barcustom_order", d: 3.67 },
      { n: "BARman_idle", d: 8.33 },
      { n: "Barserve_bottle", d: 3.0 },
      { n: "Barserve_give", d: 2.33 },
      { n: "Barserve_glass", d: 3.67 },
      { n: "Barserve_in", d: 1.67 },
      { n: "Barserve_loop", d: 2.33 },
      { n: "Barserve_order", d: 3.67 },
      { n: "dnk_stndF_loop", d: 2.33 },
      { n: "dnk_stndM_loop", d: 2.33 },
    ],
  ],
  [
    "BASEBALL",
    [
      { n: "Bat_1", d: 0.9 },
      { n: "Bat_2", d: 1.13 },
      { n: "Bat_3", d: 1.2 },
      { n: "Bat_4", d: 1.0 },
      { n: "Bat_block", d: 0.47 },
      { n: "Bat_Hit_1", d: 0.83 },
      { n: "Bat_Hit_2", d: 1.07 },
      { n: "Bat_Hit_3", d: 1.13 },
      { n: "Bat_IDLE", d: 0.93 },
      { n: "Bat_M", d: 0.53 },
      { n: "BAT_PART", d: 0.53 },
    ],
  ],
  [
    "BD_FIRE",
    [
      { n: "BD_Fire1", d: 1.83 },
      { n: "BD_Fire2", d: 1.67 },
      { n: "BD_Fire3", d: 1.83 },
      { n: "BD_GF_Wave", d: 5.07 },
      { n: "BD_Panic_01", d: 3.33 },
      { n: "BD_Panic_02", d: 3.33 },
      { n: "BD_Panic_03", d: 3.33 },
      { n: "BD_Panic_04", d: 3.33 },
      { n: "BD_Panic_Loop", d: 3.33 },
      { n: "Grlfrd_Kiss_03", d: 7.0 },
      { n: "M_smklean_loop", d: 5.0 },
      { n: "Playa_Kiss_03", d: 7.0 },
      { n: "wash_up", d: 3.0 },
    ],
  ],
  [
    "BEACH",
    [
      { n: "bather", d: 4.2 },
      { n: "Lay_Bac_Loop", d: 2.67 },
      { n: "ParkSit_M_loop", d: 3.67 },
      { n: "ParkSit_W_loop", d: 3.33 },
      { n: "SitnWait_loop_W", d: 1.33 },
    ],
  ],
  [
    "benchpress",
    [
      { n: "gym_bp_celebrate", d: 5.0 },
      { n: "gym_bp_down", d: 1.0 },
      { n: "gym_bp_getoff", d: 8.67 },
      { n: "gym_bp_geton", d: 5.33 },
      { n: "gym_bp_up_A", d: 2.33 },
      { n: "gym_bp_up_B", d: 2.67 },
      { n: "gym_bp_up_smooth", d: 1.33 },
    ],
  ],
  [
    "BF_injection",
    [
      { n: "BF_getin_LHS", d: 1.0 },
      { n: "BF_getin_RHS", d: 1.0 },
      { n: "BF_getout_LHS", d: 1.13 },
      { n: "BF_getout_RHS", d: 1.13 },
    ],
  ],
  [
    "BIKED",
    [
      { n: "BIKEd_Back", d: 0.1 },
      { n: "BIKEd_drivebyFT", d: 0.2 },
      { n: "BIKEd_drivebyLHS", d: 0.2 },
      { n: "BIKEd_drivebyRHS", d: 0.2 },
      { n: "BIKEd_Fwd", d: 0.2 },
      { n: "BIKEd_getoffBACK", d: 1.47 },
      { n: "BIKEd_getoffLHS", d: 1.0 },
      { n: "BIKEd_getoffRHS", d: 1.0 },
      { n: "BIKEd_hit", d: 0.03 },
      { n: "BIKEd_jumponL", d: 0.97 },
      { n: "BIKEd_jumponR", d: 0.97 },
      { n: "BIKEd_kick", d: 1.07 },
      { n: "BIKEd_Left", d: 0.1 },
      { n: "BIKEd_passenger", d: 0.03 },
      { n: "BIKEd_pushes", d: 0.8 },
      { n: "BIKEd_Ride", d: 0.03 },
      { n: "BIKEd_Right", d: 0.1 },
      { n: "BIKEd_shuffle", d: 0.43 },
      { n: "BIKEd_Still", d: 0.03 },
    ],
  ],
  [
    "BIKEH",
    [
      { n: "BIKEh_Back", d: 0.1 },
      { n: "BIKEh_drivebyFT", d: 0.2 },
      { n: "BIKEh_drivebyLHS", d: 0.2 },
      { n: "BIKEh_drivebyRHS", d: 0.2 },
      { n: "BIKEh_Fwd", d: 0.2 },
      { n: "BIKEh_getoffBACK", d: 1.7 },
      { n: "BIKEh_getoffLHS", d: 0.77 },
      { n: "BIKEh_getoffRHS", d: 0.73 },
      { n: "BIKEh_hit", d: 0.03 },
      { n: "BIKEh_jumponL", d: 1.47 },
      { n: "BIKEh_jumponR", d: 1.5 },
      { n: "BIKEh_kick", d: 1.07 },
      { n: "BIKEh_Left", d: 0.13 },
      { n: "BIKEh_passenger", d: 0.03 },
      { n: "BIKEh_pushes", d: 0.97 },
      { n: "BIKEh_Ride", d: 0.03 },
      { n: "BIKEh_Right", d: 0.13 },
      { n: "BIKEh_Still", d: 0.03 },
    ],
  ],
  [
    "BIKELEAP",
    [
      { n: "bk_blnce_in", d: 1.9 },
      { n: "bk_blnce_out", d: 1.0 },
      { n: "bk_jmp", d: 0.4 },
      { n: "bk_rdy_in", d: 0.5 },
      { n: "bk_rdy_out", d: 0.4 },
      { n: "struggle_cesar", d: 0.47 },
      { n: "struggle_driver", d: 0.47 },
      { n: "truck_driver", d: 0.73 },
      { n: "truck_getin", d: 2.5 },
    ],
  ],
  [
    "BIKES",
    [
      { n: "BIKEs_Back", d: 0.1 },
      { n: "BIKEs_drivebyFT", d: 0.2 },
      { n: "BIKEs_drivebyLHS", d: 0.2 },
      { n: "BIKEs_drivebyRHS", d: 0.2 },
      { n: "BIKEs_Fwd", d: 0.2 },
      { n: "BIKEs_getoffBACK", d: 2.43 },
      { n: "BIKEs_getoffLHS", d: 1.1 },
      { n: "BIKEs_getoffRHS", d: 1.1 },
      { n: "BIKEs_hit", d: 0.03 },
      { n: "BIKEs_jumponL", d: 0.9 },
      { n: "BIKEs_jumponR", d: 0.9 },
      { n: "BIKEs_kick", d: 1.0 },
      { n: "BIKEs_Left", d: 0.1 },
      { n: "BIKEs_passenger", d: 0.03 },
      { n: "BIKEs_pushes", d: 0.73 },
      { n: "BIKEs_Ride", d: 0.03 },
      { n: "BIKEs_Right", d: 0.1 },
      { n: "BIKEs_Snatch_L", d: 0.43 },
      { n: "BIKEs_Snatch_R", d: 0.43 },
      { n: "BIKEs_Still", d: 0.03 },
    ],
  ],
  [
    "BIKEV",
    [
      { n: "BIKEv_Back", d: 0.17 },
      { n: "BIKEv_drivebyFT", d: 0.17 },
      { n: "BIKEv_drivebyLHS", d: 0.23 },
      { n: "BIKEv_drivebyRHS", d: 0.2 },
      { n: "BIKEv_Fwd", d: 0.2 },
      { n: "BIKEv_getoffBACK", d: 1.7 },
      { n: "BIKEv_getoffLHS", d: 0.67 },
      { n: "BIKEv_getoffRHS", d: 0.67 },
      { n: "BIKEv_hit", d: 0.03 },
      { n: "BIKEv_jumponL", d: 0.67 },
      { n: "BIKEv_jumponR", d: 0.67 },
      { n: "BIKEv_kick", d: 1.0 },
      { n: "BIKEv_Left", d: 0.1 },
      { n: "BIKEv_passenger", d: 0.03 },
      { n: "BIKEv_pushes", d: 0.73 },
      { n: "BIKEv_Ride", d: 0.03 },
      { n: "BIKEv_Right", d: 0.1 },
      { n: "BIKEv_Still", d: 0.03 },
    ],
  ],
  [
    "BIKE_DBZ",
    [
      { n: "Pass_Driveby_BWD", d: 0.83 },
      { n: "Pass_Driveby_FWD", d: 0.83 },
      { n: "Pass_Driveby_LHS", d: 0.83 },
      { n: "Pass_Driveby_RHS", d: 0.83 },
    ],
  ],
  [
    "BLOWJOBZ",
    [
      { n: "BJ_Car_End_P", d: 4.13 },
      { n: "BJ_Car_End_W", d: 3.67 },
      { n: "BJ_Car_Loop_P", d: 0.67 },
      { n: "BJ_Car_Loop_W", d: 0.67 },
      { n: "BJ_Car_Start_P", d: 2.33 },
      { n: "BJ_Car_Start_W", d: 2.33 },
      { n: "BJ_Couch_End_P", d: 7.67 },
      { n: "BJ_Couch_End_W", d: 7.67 },
      { n: "BJ_Couch_Loop_P", d: 2.0 },
      { n: "BJ_Couch_Loop_W", d: 2.0 },
      { n: "BJ_Couch_Start_P", d: 5.33 },
      { n: "BJ_Couch_Start_W", d: 5.33 },
      { n: "BJ_Stand_End_P", d: 4.87 },
      { n: "BJ_Stand_End_W", d: 5.33 },
      { n: "BJ_Stand_Loop_P", d: 0.67 },
      { n: "BJ_Stand_Loop_W", d: 0.67 },
      { n: "BJ_Stand_Start_P", d: 2.0 },
      { n: "BJ_Stand_Start_W", d: 2.0 },
    ],
  ],
  [
    "BMX",
    [
      { n: "BMX_back", d: 0.1 },
      { n: "BMX_bunnyhop", d: 0.33 },
      { n: "BMX_drivebyFT", d: 0.2 },
      { n: "BMX_driveby_LHS", d: 0.2 },
      { n: "BMX_driveby_RHS", d: 0.2 },
      { n: "BMX_fwd", d: 0.13 },
      { n: "BMX_getoffBACK", d: 1.37 },
      { n: "BMX_getoffLHS", d: 0.73 },
      { n: "BMX_getoffRHS", d: 0.63 },
      { n: "BMX_jumponL", d: 0.9 },
      { n: "BMX_jumponR", d: 0.9 },
      { n: "BMX_Left", d: 0.13 },
      { n: "BMX_pedal", d: 0.73 },
      { n: "BMX_pushes", d: 0.8 },
      { n: "BMX_Ride", d: 0.03 },
      { n: "BMX_Right", d: 0.13 },
      { n: "BMX_sprint", d: 0.67 },
      { n: "BMX_still", d: 0.03 },
    ],
  ],
  [
    "BOMBER",
    [
      { n: "BOM_Plant", d: 2.67 },
      { n: "BOM_Plant_2Idle", d: 1.0 },
      { n: "BOM_Plant_Crouch_In", d: 0.8 },
      { n: "BOM_Plant_Crouch_Out", d: 0.8 },
      { n: "BOM_Plant_In", d: 0.87 },
      { n: "BOM_Plant_Loop", d: 0.8 },
    ],
  ],
  [
    "BOX",
    [
      { n: "boxhipin", d: 6.53 },
      { n: "boxhipup", d: 5.0 },
      { n: "boxshdwn", d: 6.1 },
      { n: "boxshup", d: 5.2 },
      { n: "bxhipwlk", d: 1.5 },
      { n: "bxhwlki", d: 0.97 },
      { n: "bxshwlk", d: 2.5 },
      { n: "bxshwlki", d: 0.97 },
      { n: "bxwlko", d: 0.53 },
      { n: "catch_box", d: 1.5 },
    ],
  ],
  [
    "BSKTBALL",
    [
      { n: "BBALL_def_jump_shot", d: 1.17 },
      { n: "BBALL_def_loop", d: 1.0 },
      { n: "BBALL_def_stepL", d: 0.6 },
      { n: "BBALL_def_stepR", d: 0.6 },
      { n: "BBALL_Dnk", d: 1.4 },
      { n: "BBALL_Dnk_Gli", d: 0.37 },
      { n: "BBALL_Dnk_Gli_O", d: 0.37 },
      { n: "BBALL_Dnk_Lnch", d: 0.2 },
      { n: "BBALL_Dnk_Lnch_O", d: 0.2 },
      { n: "BBALL_Dnk_Lnd", d: 0.93 },
      { n: "BBALL_Dnk_O", d: 0.1 },
      { n: "BBALL_idle", d: 2.43 },
      { n: "BBALL_idle2", d: 2.67 },
      { n: "BBALL_idle2_O", d: 2.67 },
      { n: "BBALL_idleloop", d: 0.67 },
      { n: "BBALL_idleloop_O", d: 0.67 },
      { n: "BBALL_idle_O", d: 2.43 },
      { n: "BBALL_Jump_Cancel", d: 1.07 },
      { n: "BBALL_Jump_Cancel_O", d: 1.07 },
      { n: "BBALL_Jump_End", d: 0.93 },
      { n: "BBALL_Jump_Shot", d: 1.67 },
      { n: "BBALL_Jump_Shot_O", d: 0.67 },
      { n: "BBALL_Net_Dnk_O", d: 1.83 },
      { n: "BBALL_pickup", d: 1.83 },
      { n: "BBALL_pickup_O", d: 1.83 },
      { n: "BBALL_react_miss", d: 0.8 },
      { n: "BBALL_react_score", d: 1.1 },
      { n: "BBALL_run", d: 0.9 },
      { n: "BBALL_run_O", d: 0.9 },
      { n: "BBALL_SkidStop_L", d: 0.5 },
      { n: "BBALL_SkidStop_L_O", d: 0.5 },
      { n: "BBALL_SkidStop_R", d: 0.5 },
      { n: "BBALL_SkidStop_R_O", d: 0.5 },
      { n: "BBALL_walk", d: 1.07 },
      { n: "BBALL_WalkStop_L", d: 0.5 },
      { n: "BBALL_WalkStop_L_O", d: 0.5 },
      { n: "BBALL_WalkStop_R", d: 0.5 },
      { n: "BBALL_WalkStop_R_O", d: 0.5 },
      { n: "BBALL_walk_O", d: 1.07 },
      { n: "BBALL_walk_start", d: 0.2 },
      { n: "BBALL_walk_start_O", d: 0.2 },
    ],
  ],
  [
    "BUDDY",
    [
      { n: "buddy_crouchfire", d: 0.87 },
      { n: "buddy_crouchreload", d: 1.1 },
      { n: "buddy_fire", d: 0.8 },
      { n: "buddy_fire_poor", d: 1.33 },
      { n: "buddy_reload", d: 1.3 },
    ],
  ],
  [
    "BUS",
    [
      { n: "BUS_close", d: 0.4 },
      { n: "BUS_getin_LHS", d: 0.33 },
      { n: "BUS_getin_RHS", d: 2.17 },
      { n: "BUS_getout_LHS", d: 0.8 },
      { n: "BUS_getout_RHS", d: 1.87 },
      { n: "BUS_jacked_LHS", d: 1.13 },
      { n: "BUS_open", d: 1.47 },
      { n: "BUS_open_RHS", d: 1.2 },
      { n: "BUS_pullout_LHS", d: 0.8 },
    ],
  ],
  [
    "CAMERA",
    [
      { n: "camcrch_cmon", d: 2.33 },
      { n: "camcrch_idleloop", d: 2.0 },
      { n: "camcrch_stay", d: 2.0 },
      { n: "camcrch_to_camstnd", d: 1.33 },
      { n: "camstnd_cmon", d: 3.0 },
      { n: "camstnd_idleloop", d: 2.0 },
      { n: "camstnd_lkabt", d: 4.33 },
      { n: "camstnd_to_camcrch", d: 1.0 },
      { n: "piccrch_in", d: 1.33 },
      { n: "piccrch_out", d: 2.0 },
      { n: "piccrch_take", d: 1.0 },
      { n: "picstnd_in", d: 1.0 },
      { n: "picstnd_out", d: 0.67 },
      { n: "picstnd_take", d: 1.0 },
    ],
  ],
  [
    "CAR",
    [
      { n: "Fixn_Car_Loop", d: 5.0 },
      { n: "Fixn_Car_Out", d: 2.33 },
      { n: "flag_drop", d: 4.5 },
      { n: "Sit_relaxed", d: 0.03 },
      { n: "Tap_hand", d: 0.33 },
      { n: "Tyd2car_bump", d: 0.83 },
      { n: "Tyd2car_high", d: 8.0 },
      { n: "Tyd2car_low", d: 6.67 },
      { n: "Tyd2car_med", d: 6.67 },
      { n: "Tyd2car_TurnL", d: 1.0 },
      { n: "Tyd2car_TurnR", d: 1.0 },
    ],
  ],
  [
    "CARRY",
    [
      { n: "crry_prtial", d: 0.03 },
      { n: "liftup", d: 1.53 },
      { n: "liftup05", d: 0.63 },
      { n: "liftup105", d: 0.67 },
      { n: "putdwn", d: 1.13 },
      { n: "putdwn05", d: 0.67 },
      { n: "putdwn105", d: 0.53 },
    ],
  ],
  [
    "CAR_CHAT",
    [
      { n: "carfone_in", d: 6.0 },
      { n: "carfone_loopA", d: 4.0 },
      { n: "carfone_loopA_to_B", d: 1.0 },
      { n: "carfone_loopB", d: 5.0 },
      { n: "carfone_loopB_to_A", d: 0.67 },
      { n: "carfone_out", d: 3.0 },
      { n: "CAR_Sc1_BL", d: 11.67 },
      { n: "CAR_Sc1_BR", d: 11.67 },
      { n: "CAR_Sc1_FL", d: 11.67 },
      { n: "CAR_Sc1_FR", d: 11.67 },
      { n: "CAR_Sc2_FL", d: 5.0 },
      { n: "CAR_Sc3_BR", d: 10.83 },
      { n: "CAR_Sc3_FL", d: 10.83 },
      { n: "CAR_Sc3_FR", d: 10.83 },
      { n: "CAR_Sc4_BL", d: 4.4 },
      { n: "CAR_Sc4_BR", d: 6.53 },
      { n: "CAR_Sc4_FL", d: 10.0 },
      { n: "CAR_Sc4_FR", d: 10.0 },
      { n: "car_talkm_in", d: 1.67 },
      { n: "car_talkm_loop", d: 4.33 },
      { n: "car_talkm_out", d: 7.33 },
    ],
  ],
  [
    "CASINO",
    [
      { n: "cards_in", d: 0.67 },
      { n: "cards_loop", d: 3.33 },
      { n: "cards_lose", d: 3.33 },
      { n: "cards_out", d: 0.67 },
      { n: "cards_pick_01", d: 4.67 },
      { n: "cards_pick_02", d: 5.33 },
      { n: "cards_raise", d: 1.67 },
      { n: "cards_win", d: 3.0 },
      { n: "dealone", d: 0.8 },
      { n: "manwinb", d: 1.5 },
      { n: "manwind", d: 1.67 },
      { n: "Roulette_bet", d: 2.33 },
      { n: "Roulette_in", d: 0.67 },
      { n: "Roulette_loop", d: 3.67 },
      { n: "Roulette_lose", d: 2.67 },
      { n: "Roulette_out", d: 0.67 },
      { n: "Roulette_win", d: 2.33 },
      { n: "Slot_bet_01", d: 4.67 },
      { n: "Slot_bet_02", d: 2.0 },
      { n: "Slot_in", d: 3.67 },
      { n: "Slot_lose_out", d: 4.0 },
      { n: "Slot_Plyr", d: 1.33 },
      { n: "Slot_wait", d: 3.67 },
      { n: "Slot_win_out", d: 9.33 },
      { n: "wof", d: 1.47 },
    ],
  ],
  [
    "CHAINSAW",
    [
      { n: "CSAW_1", d: 1.0 },
      { n: "CSAW_2", d: 1.03 },
      { n: "CSAW_3", d: 0.87 },
      { n: "CSAW_G", d: 1.17 },
      { n: "CSAW_Hit_1", d: 0.83 },
      { n: "CSAW_Hit_2", d: 1.07 },
      { n: "CSAW_Hit_3", d: 1.13 },
      { n: "csaw_part", d: 0.13 },
      { n: "IDLE_csaw", d: 1.5 },
      { n: "WEAPON_csaw", d: 1.33 },
      { n: "WEAPON_csawlo", d: 1.9 },
    ],
  ],
  [
    "CHOPPA",
    [
      { n: "CHOPPA_back", d: 0.1 },
      { n: "CHOPPA_bunnyhop", d: 0.33 },
      { n: "CHOPPA_drivebyFT", d: 0.2 },
      { n: "CHOPPA_driveby_LHS", d: 0.2 },
      { n: "CHOPPA_driveby_RHS", d: 0.2 },
      { n: "CHOPPA_fwd", d: 0.2 },
      { n: "CHOPPA_getoffBACK", d: 1.27 },
      { n: "CHOPPA_getoffLHS", d: 0.73 },
      { n: "CHOPPA_getoffRHS", d: 0.63 },
      { n: "CHOPPA_jumponL", d: 0.7 },
      { n: "CHOPPA_jumponR", d: 0.8 },
      { n: "CHOPPA_Left", d: 0.13 },
      { n: "CHOPPA_pedal", d: 0.73 },
      { n: "CHOPPA_Pushes", d: 0.8 },
      { n: "CHOPPA_ride", d: 0.03 },
      { n: "CHOPPA_Right", d: 0.13 },
      { n: "CHOPPA_sprint", d: 0.67 },
      { n: "CHOPPA_Still", d: 0.03 },
    ],
  ],
  [
    "CLOTHES",
    [
      { n: "CLO_Buy", d: 2.07 },
      { n: "CLO_In", d: 4.0 },
      { n: "CLO_Out", d: 2.67 },
      { n: "CLO_Pose_Hat", d: 3.33 },
      { n: "CLO_Pose_In", d: 3.13 },
      { n: "CLO_Pose_In_O", d: 4.0 },
      { n: "CLO_Pose_Legs", d: 3.33 },
      { n: "CLO_Pose_Loop", d: 6.0 },
      { n: "CLO_Pose_Out", d: 4.0 },
      { n: "CLO_Pose_Out_O", d: 4.0 },
      { n: "CLO_Pose_Shoes", d: 3.33 },
      { n: "CLO_Pose_Torso", d: 3.33 },
      { n: "CLO_Pose_Watch", d: 3.33 },
    ],
  ],
  [
    "COACH",
    [
      { n: "COACH_inL", d: 2.17 },
      { n: "COACH_inR", d: 2.2 },
      { n: "COACH_opnL", d: 1.2 },
      { n: "COACH_opnR", d: 1.2 },
      { n: "COACH_outL", d: 1.73 },
      { n: "COACH_outR", d: 1.83 },
    ],
  ],
  [
    "COLT45",
    [
      { n: "2guns_crouchfire", d: 0.8 },
      { n: "colt45_crouchfire", d: 0.8 },
      { n: "colt45_crouchreload", d: 1.0 },
      { n: "colt45_fire", d: 0.73 },
      { n: "colt45_fire_2hands", d: 0.87 },
      { n: "colt45_reload", d: 0.93 },
      { n: "sawnoff_reload", d: 0.93 },
    ],
  ],
  [
    "COP_AMBIENT",
    [
      { n: "Copbrowse_in", d: 5.0 },
      { n: "Copbrowse_loop", d: 2.33 },
      { n: "Copbrowse_nod", d: 4.0 },
      { n: "Copbrowse_out", d: 2.67 },
      { n: "Copbrowse_shake", d: 1.83 },
      { n: "Coplook_in", d: 1.33 },
      { n: "Coplook_loop", d: 2.67 },
      { n: "Coplook_nod", d: 5.33 },
      { n: "Coplook_out", d: 0.67 },
      { n: "Coplook_shake", d: 4.0 },
      { n: "Coplook_think", d: 3.33 },
      { n: "Coplook_watch", d: 2.0 },
    ],
  ],
  [
    "COP_DVBYZ",
    [
      { n: "COP_Dvby_B", d: 0.83 },
      { n: "COP_Dvby_FT", d: 0.83 },
      { n: "COP_Dvby_L", d: 0.83 },
      { n: "COP_Dvby_R", d: 0.83 },
    ],
  ],
  [
    "CRACK",
    [
      { n: "Bbalbat_Idle_01", d: 6.67 },
      { n: "Bbalbat_Idle_02", d: 10.0 },
      { n: "crckdeth1", d: 2.17 },
      { n: "crckdeth2", d: 3.0 },
      { n: "crckdeth3", d: 2.17 },
      { n: "crckdeth4", d: 1.67 },
      { n: "crckidle1", d: 3.5 },
      { n: "crckidle2", d: 3.33 },
      { n: "crckidle3", d: 3.33 },
      { n: "crckidle4", d: 2.67 },
    ],
  ],
  [
    "CRIB",
    [
      { n: "CRIB_Console_Loop", d: 3.0 },
      { n: "CRIB_Use_Switch", d: 1.17 },
      { n: "PED_Console_Loop", d: 3.0 },
      { n: "PED_Console_Loose", d: 3.5 },
      { n: "PED_Console_Win", d: 3.5 },
    ],
  ],
  [
    "DAM_JUMP",
    [
      { n: "DAM_Dive_Loop", d: 1.33 },
      { n: "DAM_Land", d: 2.6 },
      { n: "DAM_Launch", d: 2.4 },
      { n: "Jump_Roll", d: 3.17 },
      { n: "SF_JumpWall", d: 3.0 },
    ],
  ],
  [
    "DANCING",
    [
      { n: "bd_clap", d: 3.2 },
      { n: "bd_clap1", d: 2.63 },
      { n: "dance_loop", d: 1.17 },
      { n: "DAN_Down_A", d: 1.0 },
      { n: "DAN_Left_A", d: 1.0 },
      { n: "DAN_Loop_A", d: 2.0 },
      { n: "DAN_Right_A", d: 1.0 },
      { n: "DAN_Up_A", d: 1.0 },
      { n: "dnce_M_a", d: 2.13 },
      { n: "dnce_M_b", d: 1.93 },
      { n: "dnce_M_c", d: 1.93 },
      { n: "dnce_M_d", d: 2.43 },
      { n: "dnce_M_e", d: 0.9 },
    ],
  ],
  [
    "DEALER",
    [
      { n: "DEALER_DEAL", d: 3.17 },
      { n: "DEALER_IDLE", d: 6.67 },
      { n: "DEALER_IDLE_01", d: 5.0 },
      { n: "DEALER_IDLE_02", d: 4.0 },
      { n: "DEALER_IDLE_03", d: 4.67 },
      { n: "DRUGS_BUY", d: 3.17 },
      { n: "shop_pay", d: 4.67 },
    ],
  ],
  [
    "DILDO",
    [
      { n: "DILDO_1", d: 0.97 },
      { n: "DILDO_2", d: 1.1 },
      { n: "DILDO_3", d: 1.17 },
      { n: "DILDO_block", d: 0.47 },
      { n: "DILDO_G", d: 1.47 },
      { n: "DILDO_Hit_1", d: 0.77 },
      { n: "DILDO_Hit_2", d: 1.03 },
      { n: "DILDO_Hit_3", d: 0.9 },
      { n: "DILDO_IDLE", d: 0.87 },
    ],
  ],
  [
    "DODGE",
    [
      { n: "Cover_Dive_01", d: 6.0 },
      { n: "Cover_Dive_02", d: 6.0 },
      { n: "Crushed", d: 0.93 },
      { n: "Crush_Jump", d: 3.17 },
    ],
  ],
  [
    "DOZER",
    [
      { n: "DOZER_Align_LHS", d: 0.97 },
      { n: "DOZER_Align_RHS", d: 0.93 },
      { n: "DOZER_getin_LHS", d: 0.43 },
      { n: "DOZER_getin_RHS", d: 0.43 },
      { n: "DOZER_getout_LHS", d: 1.07 },
      { n: "DOZER_getout_RHS", d: 0.77 },
      { n: "DOZER_Jacked_LHS", d: 1.27 },
      { n: "DOZER_Jacked_RHS", d: 1.07 },
      { n: "DOZER_pullout_LHS", d: 0.73 },
      { n: "DOZER_pullout_RHS", d: 0.7 },
    ],
  ],
  [
    "DRIVEBYS",
    [
      { n: "Gang_DrivebyLHS", d: 0.83 },
      { n: "Gang_DrivebyLHS_Bwd", d: 0.83 },
      { n: "Gang_DrivebyLHS_Fwd", d: 0.83 },
      { n: "Gang_DrivebyRHS", d: 0.83 },
      { n: "Gang_DrivebyRHS_Bwd", d: 0.83 },
      { n: "Gang_DrivebyRHS_Fwd", d: 0.83 },
      { n: "Gang_DrivebyTop_LHS", d: 0.83 },
      { n: "Gang_DrivebyTop_RHS", d: 0.83 },
    ],
  ],
  [
    "FAT",
    [
      { n: "FatIdle", d: 1.5 },
      { n: "FatIdle_armed", d: 1.53 },
      { n: "FatIdle_Csaw", d: 1.5 },
      { n: "FatIdle_Rocket", d: 1.6 },
      { n: "FatRun", d: 0.77 },
      { n: "FatRun_armed", d: 0.77 },
      { n: "FatRun_Csaw", d: 0.77 },
      { n: "FatRun_Rocket", d: 0.77 },
      { n: "FatSprint", d: 0.6 },
      { n: "FatWalk", d: 1.17 },
      { n: "FatWalkstart", d: 0.2 },
      { n: "FatWalkstart_Csaw", d: 0.2 },
      { n: "FatWalkSt_armed", d: 0.2 },
      { n: "FatWalkSt_Rocket", d: 0.2 },
      { n: "FatWalk_armed", d: 1.17 },
      { n: "FatWalk_Csaw", d: 1.17 },
      { n: "FatWalk_Rocket", d: 1.17 },
      { n: "IDLE_tired", d: 1.07 },
    ],
  ],
  [
    "FIGHT_B",
    [
      { n: "FightB_1", d: 0.73 },
      { n: "FightB_2", d: 1.1 },
      { n: "FightB_3", d: 1.2 },
      { n: "FightB_block", d: 0.47 },
      { n: "FightB_G", d: 1.07 },
      { n: "FightB_IDLE", d: 0.8 },
      { n: "FightB_M", d: 0.5 },
      { n: "HitB_1", d: 0.73 },
      { n: "HitB_2", d: 0.83 },
      { n: "HitB_3", d: 1.43 },
    ],
  ],
  [
    "FIGHT_C",
    [
      { n: "FightC_1", d: 0.83 },
      { n: "FightC_2", d: 1.03 },
      { n: "FightC_3", d: 1.0 },
      { n: "FightC_block", d: 0.47 },
      { n: "FightC_blocking", d: 3.2 },
      { n: "FightC_G", d: 0.77 },
      { n: "FightC_IDLE", d: 1.0 },
      { n: "FightC_M", d: 0.9 },
      { n: "FightC_Spar", d: 3.2 },
      { n: "HitC_1", d: 0.3 },
      { n: "HitC_2", d: 0.67 },
      { n: "HitC_3", d: 0.83 },
    ],
  ],
  [
    "FIGHT_D",
    [
      { n: "FightD_1", d: 0.93 },
      { n: "FightD_2", d: 1.87 },
      { n: "FightD_3", d: 0.9 },
      { n: "FightD_block", d: 0.47 },
      { n: "FightD_G", d: 0.83 },
      { n: "FightD_IDLE", d: 1.53 },
      { n: "FightD_M", d: 1.07 },
      { n: "HitD_1", d: 0.67 },
      { n: "HitD_2", d: 1.83 },
      { n: "HitD_3", d: 0.97 },
    ],
  ],
  [
    "FIGHT_E",
    [
      { n: "FightKick", d: 0.77 },
      { n: "FightKick_B", d: 1.03 },
      { n: "Hit_fightkick", d: 0.5 },
      { n: "Hit_fightkick_B", d: 1.13 },
    ],
  ],
  [
    "FINALE",
    [
      { n: "FIN_Climb_In", d: 2.9 },
      { n: "FIN_Cop1_ClimbOut2", d: 6.0 },
      { n: "FIN_Cop1_Loop", d: 2.0 },
      { n: "FIN_Cop1_Stomp", d: 1.0 },
      { n: "FIN_Hang_L", d: 0.57 },
      { n: "FIN_Hang_Loop", d: 4.0 },
      { n: "FIN_Hang_R", d: 0.57 },
      { n: "FIN_Hang_Slip", d: 3.33 },
      { n: "FIN_Jump_On", d: 5.6 },
      { n: "FIN_Land_Car", d: 0.67 },
      { n: "FIN_Land_Die", d: 2.37 },
      { n: "FIN_LegsUp", d: 1.0 },
      { n: "FIN_LegsUp_L", d: 0.5 },
      { n: "FIN_LegsUp_Loop", d: 1.33 },
      { n: "FIN_LegsUp_R", d: 0.5 },
      { n: "FIN_Let_Go", d: 0.17 },
    ],
  ],
  [
    "FINALE2",
    [
      { n: "FIN_Cop1_ClimbOut", d: 4.0 },
      { n: "FIN_Cop1_Fall", d: 0.43 },
      { n: "FIN_Cop1_Loop", d: 2.0 },
      { n: "FIN_Cop1_Shot", d: 2.07 },
      { n: "FIN_Cop1_Swing", d: 1.17 },
      { n: "FIN_Cop2_ClimbOut", d: 5.33 },
      { n: "FIN_Switch_P", d: 3.97 },
      { n: "FIN_Switch_S", d: 2.17 },
    ],
  ],
  ["FLAME", [{ n: "FLAME_fire", d: 0.8 }]],
  [
    "Flowers",
    [
      { n: "Flower_attack", d: 0.8 },
      { n: "Flower_attack_M", d: 1.23 },
      { n: "Flower_Hit", d: 0.83 },
    ],
  ],
  [
    "FOOD",
    [
      { n: "EAT_Burger", d: 5.0 },
      { n: "EAT_Chicken", d: 5.0 },
      { n: "EAT_Pizza", d: 5.0 },
      { n: "EAT_Vomit_P", d: 8.0 },
      { n: "EAT_Vomit_SK", d: 8.0 },
      { n: "FF_Dam_Bkw", d: 0.67 },
      { n: "FF_Dam_Fwd", d: 0.67 },
      { n: "FF_Dam_Left", d: 0.67 },
      { n: "FF_Dam_Right", d: 0.67 },
      { n: "FF_Die_Bkw", d: 0.67 },
      { n: "FF_Die_Fwd", d: 0.67 },
      { n: "FF_Die_Left", d: 0.67 },
      { n: "FF_Die_Right", d: 0.67 },
      { n: "FF_Sit_Eat1", d: 2.83 },
      { n: "FF_Sit_Eat2", d: 2.67 },
      { n: "FF_Sit_Eat3", d: 2.67 },
      { n: "FF_Sit_In", d: 3.0 },
      { n: "FF_Sit_In_L", d: 2.0 },
      { n: "FF_Sit_In_R", d: 2.0 },
      { n: "FF_Sit_Look", d: 8.0 },
      { n: "FF_Sit_Loop", d: 2.67 },
      { n: "FF_Sit_Out_180", d: 2.83 },
      { n: "FF_Sit_Out_L_180", d: 1.33 },
      { n: "FF_Sit_Out_R_180", d: 1.33 },
      { n: "SHP_Thank", d: 1.17 },
      { n: "SHP_Tray_In", d: 0.67 },
      { n: "SHP_Tray_Lift", d: 1.67 },
      { n: "SHP_Tray_Lift_In", d: 0.5 },
      { n: "SHP_Tray_Lift_Loop", d: 8.0 },
      { n: "SHP_Tray_Lift_Out", d: 0.5 },
      { n: "SHP_Tray_Out", d: 0.67 },
      { n: "SHP_Tray_Pose", d: 0.67 },
      { n: "SHP_Tray_Return", d: 1.33 },
    ],
  ],
  [
    "Freeweights",
    [
      { n: "gym_barbell", d: 2.37 },
      { n: "gym_free_A", d: 1.93 },
      { n: "gym_free_B", d: 2.33 },
      { n: "gym_free_celebrate", d: 3.33 },
      { n: "gym_free_down", d: 0.57 },
      { n: "gym_free_loop", d: 0.67 },
      { n: "gym_free_pickup", d: 3.17 },
      { n: "gym_free_putdown", d: 3.17 },
      { n: "gym_free_up_smooth", d: 1.0 },
    ],
  ],
  [
    "GANGS",
    [
      { n: "DEALER_DEAL", d: 1.17 },
      { n: "DEALER_IDLE", d: 2.0 },
      { n: "drnkbr_prtl", d: 2.67 },
      { n: "drnkbr_prtl_F", d: 2.67 },
      { n: "DRUGS_BUY", d: 1.17 },
      { n: "hndshkaa", d: 4.0 },
      { n: "hndshkba", d: 2.33 },
      { n: "hndshkca", d: 3.33 },
      { n: "hndshkcb", d: 3.33 },
      { n: "hndshkda", d: 2.0 },
      { n: "hndshkea", d: 1.0 },
      { n: "hndshkfa", d: 4.17 },
      { n: "hndshkfa_swt", d: 4.17 },
      { n: "Invite_No", d: 3.33 },
      { n: "Invite_Yes", d: 4.33 },
      { n: "leanIDLE", d: 1.0 },
      { n: "leanIN", d: 1.0 },
      { n: "leanOUT", d: 1.0 },
      { n: "prtial_gngtlkA", d: 4.0 },
      { n: "prtial_gngtlkB", d: 6.17 },
      { n: "prtial_gngtlkC", d: 7.33 },
      { n: "prtial_gngtlkD", d: 3.0 },
      { n: "prtial_gngtlkE", d: 2.83 },
      { n: "prtial_gngtlkF", d: 5.17 },
      { n: "prtial_gngtlkG", d: 7.0 },
      { n: "prtial_gngtlkH", d: 6.0 },
      { n: "prtial_hndshk_01", d: 1.67 },
      { n: "prtial_hndshk_biz_01", d: 2.33 },
      { n: "shake_cara", d: 1.67 },
      { n: "shake_carK", d: 1.27 },
      { n: "shake_carSH", d: 1.5 },
      { n: "smkcig_prtl", d: 7.5 },
      { n: "smkcig_prtl_F", d: 7.5 },
    ],
  ],
  [
    "GFUNK",
    [
      { n: "Dance_B1", d: 1.27 },
      { n: "Dance_B2", d: 1.27 },
      { n: "Dance_B3", d: 1.27 },
      { n: "Dance_B4", d: 1.27 },
      { n: "Dance_B5", d: 1.27 },
      { n: "Dance_B6", d: 1.27 },
      { n: "Dance_B7", d: 1.27 },
      { n: "Dance_B8", d: 1.27 },
      { n: "Dance_B9", d: 1.27 },
      { n: "Dance_B10", d: 1.27 },
      { n: "Dance_B11", d: 1.27 },
      { n: "Dance_B12", d: 1.27 },
      { n: "Dance_B13", d: 1.27 },
      { n: "Dance_B14", d: 1.27 },
      { n: "Dance_B15", d: 1.27 },
      { n: "Dance_B16", d: 1.27 },
      { n: "Dance_G1", d: 1.27 },
      { n: "Dance_G2", d: 1.27 },
      { n: "Dance_G3", d: 1.27 },
      { n: "Dance_G4", d: 1.27 },
      { n: "Dance_G5", d: 1.27 },
      { n: "Dance_G6", d: 1.27 },
      { n: "Dance_G7", d: 1.27 },
      { n: "Dance_G8", d: 1.27 },
      { n: "Dance_G9", d: 1.27 },
      { n: "Dance_G10", d: 1.27 },
      { n: "Dance_G11", d: 1.27 },
      { n: "Dance_G12", d: 1.27 },
      { n: "Dance_G13", d: 1.27 },
      { n: "Dance_G14", d: 1.27 },
      { n: "Dance_G15", d: 1.27 },
      { n: "Dance_G16", d: 1.27 },
      { n: "dance_loop", d: 1.17 },
    ],
  ],
  [
    "GHANDS",
    [
      { n: "gsign1", d: 4.77 },
      { n: "gsign1LH", d: 2.73 },
      { n: "gsign2", d: 2.13 },
      { n: "gsign2LH", d: 2.33 },
      { n: "gsign3", d: 4.67 },
      { n: "gsign3LH", d: 2.0 },
      { n: "gsign4", d: 4.17 },
      { n: "gsign4LH", d: 4.67 },
      { n: "gsign5", d: 6.2 },
      { n: "gsign5LH", d: 2.0 },
      { n: "LHGsign1", d: 2.0 },
      { n: "LHGsign2", d: 2.0 },
      { n: "LHGsign3", d: 2.0 },
      { n: "LHGsign4", d: 2.0 },
      { n: "LHGsign5", d: 2.0 },
      { n: "RHGsign1", d: 2.0 },
      { n: "RHGsign2", d: 2.0 },
      { n: "RHGsign3", d: 2.0 },
      { n: "RHGsign4", d: 2.0 },
      { n: "RHGsign5", d: 2.0 },
    ],
  ],
  [
    "GHETTO_DB",
    [
      { n: "GDB_Car2_PLY", d: 9.5 },
      { n: "GDB_Car2_SMO", d: 9.5 },
      { n: "GDB_Car2_SWE", d: 9.5 },
      { n: "GDB_Car_PLY", d: 13.33 },
      { n: "GDB_Car_RYD", d: 13.33 },
      { n: "GDB_Car_SMO", d: 13.33 },
      { n: "GDB_Car_SWE", d: 13.33 },
    ],
  ],
  ["goggles", [{ n: "goggles_put_on", d: 0.8 }]],
  [
    "GRAFFITI",
    [
      { n: "graffiti_Chkout", d: 4.67 },
      { n: "spraycan_fire", d: 2.33 },
    ],
  ],
  [
    "GRAVEYARD",
    [
      { n: "mrnF_loop", d: 4.67 },
      { n: "mrnM_loop", d: 2.67 },
      { n: "prst_loopa", d: 4.0 },
    ],
  ],
  [
    "GRENADE",
    [
      { n: "WEAPON_start_throw", d: 0.2 },
      { n: "WEAPON_throw", d: 0.87 },
      { n: "WEAPON_throwu", d: 0.67 },
    ],
  ],
  [
    "GYMNASIUM",
    [
      { n: "GYMshadowbox", d: 5.1 },
      { n: "gym_bike_celebrate", d: 1.93 },
      { n: "gym_bike_fast", d: 0.4 },
      { n: "gym_bike_faster", d: 0.4 },
      { n: "gym_bike_getoff", d: 1.67 },
      { n: "gym_bike_geton", d: 1.67 },
      { n: "gym_bike_pedal", d: 0.4 },
      { n: "gym_bike_slow", d: 0.43 },
      { n: "gym_bike_still", d: 1.67 },
      { n: "gym_jog_falloff", d: 2.17 },
      { n: "gym_shadowbox", d: 5.1 },
      { n: "gym_tread_celebrate", d: 2.5 },
      { n: "gym_tread_falloff", d: 2.0 },
      { n: "gym_tread_getoff", d: 3.33 },
      { n: "gym_tread_geton", d: 2.5 },
      { n: "gym_tread_jog", d: 0.77 },
      { n: "gym_tread_sprint", d: 0.67 },
      { n: "gym_tread_tired", d: 1.33 },
      { n: "gym_tread_walk", d: 1.07 },
      { n: "gym_walk_falloff", d: 3.33 },
      { n: "Pedals_fast", d: 0.4 },
      { n: "Pedals_med", d: 0.4 },
      { n: "Pedals_slow", d: 0.43 },
      { n: "Pedals_still", d: 0.43 },
    ],
  ],
  [
    "HAIRCUTS",
    [
      { n: "BRB_Beard_01", d: 4.5 },
      { n: "BRB_Buy", d: 4.17 },
      { n: "BRB_Cut", d: 1.7 },
      { n: "BRB_Cut_In", d: 0.83 },
      { n: "BRB_Cut_Out", d: 1.33 },
      { n: "BRB_Hair_01", d: 3.83 },
      { n: "BRB_Hair_02", d: 4.5 },
      { n: "BRB_In", d: 1.33 },
      { n: "BRB_Loop", d: 2.67 },
      { n: "BRB_Out", d: 0.67 },
      { n: "BRB_Sit_In", d: 2.07 },
      { n: "BRB_Sit_Loop", d: 7.0 },
      { n: "BRB_Sit_Out", d: 3.0 },
    ],
  ],
  [
    "HEIST9",
    [
      { n: "CAS_G2_GasKO", d: 3.33 },
      { n: "swt_wllpk_L", d: 2.67 },
      { n: "swt_wllpk_L_back", d: 0.5 },
      { n: "swt_wllpk_R", d: 3.67 },
      { n: "swt_wllpk_R_back", d: 0.43 },
      { n: "swt_wllshoot_in_L", d: 1.0 },
      { n: "swt_wllshoot_in_R", d: 1.3 },
      { n: "swt_wllshoot_out_L", d: 2.0 },
      { n: "swt_wllshoot_out_R", d: 1.43 },
      { n: "Use_SwipeCard", d: 1.17 },
    ],
  ],
  [
    "INT_HOUSE",
    [
      { n: "BED_In_L", d: 3.33 },
      { n: "BED_In_R", d: 3.33 },
      { n: "BED_Loop_L", d: 3.33 },
      { n: "BED_Loop_R", d: 3.33 },
      { n: "BED_Out_L", d: 3.33 },
      { n: "BED_Out_R", d: 3.33 },
      { n: "LOU_In", d: 1.83 },
      { n: "LOU_Loop", d: 3.33 },
      { n: "LOU_Out", d: 2.0 },
      { n: "wash_up", d: 3.0 },
    ],
  ],
  [
    "INT_OFFICE",
    [
      { n: "FF_Dam_Fwd", d: 0.67 },
      { n: "OFF_Sit_2Idle_180", d: 2.83 },
      { n: "OFF_Sit_Bored_Loop", d: 2.83 },
      { n: "OFF_Sit_Crash", d: 3.33 },
      { n: "OFF_Sit_Drink", d: 4.17 },
      { n: "OFF_Sit_Idle_Loop", d: 2.07 },
      { n: "OFF_Sit_In", d: 2.77 },
      { n: "OFF_Sit_Read", d: 3.33 },
      { n: "OFF_Sit_Type_Loop", d: 3.33 },
      { n: "OFF_Sit_Watch", d: 2.0 },
    ],
  ],
  [
    "INT_SHOP",
    [
      { n: "shop_cashier", d: 6.67 },
      { n: "shop_in", d: 1.0 },
      { n: "shop_lookA", d: 2.0 },
      { n: "shop_lookB", d: 3.0 },
      { n: "shop_loop", d: 2.0 },
      { n: "shop_out", d: 1.33 },
      { n: "shop_pay", d: 6.67 },
      { n: "shop_shelf", d: 2.33 },
    ],
  ],
  [
    "JST_BUISNESS",
    [
      { n: "girl_01", d: 3.33 },
      { n: "girl_02", d: 11.33 },
      { n: "player_01", d: 24.83 },
      { n: "smoke_01", d: 25.0 },
    ],
  ],
  [
    "KART",
    [
      { n: "KART_getin_LHS", d: 0.83 },
      { n: "KART_getin_RHS", d: 0.83 },
      { n: "KART_getout_LHS", d: 0.83 },
      { n: "KART_getout_RHS", d: 0.83 },
    ],
  ],
  [
    "KISSING",
    [
      { n: "BD_GF_Wave", d: 5.07 },
      { n: "gfwave2", d: 2.67 },
      { n: "GF_CarArgue_01", d: 5.0 },
      { n: "GF_CarArgue_02", d: 5.0 },
      { n: "GF_CarSpot", d: 5.0 },
      { n: "GF_StreetArgue_01", d: 5.0 },
      { n: "GF_StreetArgue_02", d: 5.0 },
      { n: "gift_get", d: 5.33 },
      { n: "gift_give", d: 5.33 },
      { n: "Grlfrd_Kiss_01", d: 4.17 },
      { n: "Grlfrd_Kiss_02", d: 5.77 },
      { n: "Grlfrd_Kiss_03", d: 7.0 },
      { n: "Playa_Kiss_01", d: 5.0 },
      { n: "Playa_Kiss_02", d: 5.77 },
      { n: "Playa_Kiss_03", d: 7.0 },
    ],
  ],
  [
    "KNIFE",
    [
      { n: "KILL_Knife_Ped_Damage", d: 2.23 },
      { n: "KILL_Knife_Ped_Die", d: 1.93 },
      { n: "KILL_Knife_Player", d: 2.67 },
      { n: "KILL_Partial", d: 0.03 },
      { n: "knife_1", d: 1.0 },
      { n: "knife_2", d: 0.93 },
      { n: "knife_3", d: 0.87 },
      { n: "Knife_4", d: 0.9 },
      { n: "knife_block", d: 0.47 },
      { n: "Knife_G", d: 0.9 },
      { n: "knife_hit_1", d: 0.57 },
      { n: "knife_hit_2", d: 0.63 },
      { n: "knife_hit_3", d: 1.6 },
      { n: "knife_IDLE", d: 1.3 },
      { n: "knife_part", d: 0.53 },
      { n: "WEAPON_knifeidle", d: 1.3 },
    ],
  ],
  [
    "LAPDAN1",
    [
      { n: "LAPDAN_D", d: 37.73 },
      { n: "LAPDAN_P", d: 37.73 },
    ],
  ],
  [
    "LAPDAN2",
    [
      { n: "LAPDAN_D", d: 46.83 },
      { n: "LAPDAN_P", d: 46.83 },
    ],
  ],
  [
    "LAPDAN3",
    [
      { n: "LAPDAN_D", d: 51.47 },
      { n: "LAPDAN_P", d: 51.47 },
    ],
  ],
  [
    "LOWRIDER",
    [
      { n: "F_smklean_loop", d: 4.0 },
      { n: "lrgirl_bdbnce", d: 2.67 },
      { n: "lrgirl_hair", d: 2.33 },
      { n: "lrgirl_hurry", d: 2.83 },
      { n: "lrgirl_idleloop", d: 2.17 },
      { n: "lrgirl_idle_to_l0", d: 2.17 },
      { n: "lrgirl_l0_bnce", d: 0.67 },
      { n: "lrgirl_l0_loop", d: 2.0 },
      { n: "lrgirl_l0_to_l1", d: 3.67 },
      { n: "lrgirl_l12_to_l0", d: 2.0 },
      { n: "lrgirl_l1_bnce", d: 0.67 },
      { n: "lrgirl_l1_loop", d: 2.0 },
      { n: "lrgirl_l1_to_l2", d: 1.33 },
      { n: "lrgirl_l2_bnce", d: 0.67 },
      { n: "lrgirl_l2_loop", d: 1.5 },
      { n: "lrgirl_l2_to_l3", d: 1.5 },
      { n: "lrgirl_l345_to_l1", d: 1.0 },
      { n: "lrgirl_l3_bnce", d: 0.67 },
      { n: "lrgirl_l3_loop", d: 2.0 },
      { n: "lrgirl_l3_to_l4", d: 0.67 },
      { n: "lrgirl_l4_bnce", d: 0.67 },
      { n: "lrgirl_l4_loop", d: 2.33 },
      { n: "lrgirl_l4_to_l5", d: 1.0 },
      { n: "lrgirl_l5_bnce", d: 0.83 },
      { n: "lrgirl_l5_loop", d: 1.67 },
      { n: "M_smklean_loop", d: 5.0 },
      { n: "M_smkstnd_loop", d: 5.33 },
      { n: "prtial_gngtlkB", d: 1.47 },
      { n: "prtial_gngtlkC", d: 1.5 },
      { n: "prtial_gngtlkD", d: 2.47 },
      { n: "prtial_gngtlkE", d: 3.0 },
      { n: "prtial_gngtlkF", d: 2.67 },
      { n: "prtial_gngtlkG", d: 2.67 },
      { n: "prtial_gngtlkH", d: 3.33 },
      { n: "RAP_A_Loop", d: 2.67 },
      { n: "RAP_B_Loop", d: 2.67 },
      { n: "RAP_C_Loop", d: 3.0 },
      { n: "Sit_relaxed", d: 0.03 },
      { n: "Tap_hand", d: 0.33 },
    ],
  ],
  [
    "MD_CHASE",
    [
      { n: "Carhit_Hangon", d: 1.53 },
      { n: "Carhit_Tumble", d: 2.03 },
      { n: "donutdrop", d: 1.5 },
      { n: "Fen_Choppa_L1", d: 1.43 },
      { n: "Fen_Choppa_L2", d: 1.3 },
      { n: "Fen_Choppa_L3", d: 1.3 },
      { n: "Fen_Choppa_R1", d: 1.3 },
      { n: "Fen_Choppa_R2", d: 1.3 },
      { n: "Fen_Choppa_R3", d: 1.3 },
      { n: "Hangon_Stun_loop", d: 4.67 },
      { n: "Hangon_Stun_Turn", d: 4.0 },
      { n: "MD_BIKE_2_HANG", d: 1.37 },
      { n: "MD_BIKE_Jmp_BL", d: 1.1 },
      { n: "MD_BIKE_Jmp_F", d: 1.0 },
      { n: "MD_BIKE_Lnd_BL", d: 0.9 },
      { n: "MD_BIKE_Lnd_Die_BL", d: 1.53 },
      { n: "MD_BIKE_Lnd_Die_F", d: 0.8 },
      { n: "MD_BIKE_Lnd_F", d: 1.17 },
      { n: "MD_BIKE_Lnd_Roll", d: 2.7 },
      { n: "MD_BIKE_Lnd_Roll_F", d: 1.03 },
      { n: "MD_BIKE_Punch", d: 1.83 },
      { n: "MD_BIKE_Punch_F", d: 1.83 },
      { n: "MD_BIKE_Shot_F", d: 1.33 },
      { n: "MD_HANG_Lnd_Roll", d: 2.7 },
      { n: "MD_HANG_Loop", d: 1.0 },
    ],
  ],
  [
    "MD_END",
    [
      { n: "END_SC1_PLY", d: 5.0 },
      { n: "END_SC1_RYD", d: 5.0 },
      { n: "END_SC1_SMO", d: 5.0 },
      { n: "END_SC1_SWE", d: 5.0 },
      { n: "END_SC2_PLY", d: 9.0 },
      { n: "END_SC2_RYD", d: 9.0 },
      { n: "END_SC2_SMO", d: 9.0 },
      { n: "END_SC2_SWE", d: 9.0 },
    ],
  ],
  ["MEDIC", [{ n: "CPR", d: 8.33 }]],
  [
    "MISC",
    [
      { n: "bitchslap", d: 1.17 },
      { n: "BMX_celebrate", d: 1.57 },
      { n: "BMX_comeon", d: 0.77 },
      { n: "bmx_idleloop_01", d: 3.33 },
      { n: "bmx_idleloop_02", d: 6.67 },
      { n: "bmx_talkleft_in", d: 0.67 },
      { n: "bmx_talkleft_loop", d: 6.67 },
      { n: "bmx_talkleft_out", d: 0.67 },
      { n: "bmx_talkright_in", d: 0.67 },
      { n: "bmx_talkright_loop", d: 7.33 },
      { n: "bmx_talkright_out", d: 0.67 },
      { n: "bng_wndw", d: 7.33 },
      { n: "bng_wndw_02", d: 7.33 },
      { n: "Case_pickup", d: 1.0 },
      { n: "door_jet", d: 5.33 },
      { n: "GRAB_L", d: 0.4 },
      { n: "GRAB_R", d: 0.4 },
      { n: "Hiker_Pose", d: 0.33 },
      { n: "Hiker_Pose_L", d: 0.33 },
      { n: "Idle_Chat_02", d: 7.23 },
      { n: "KAT_Throw_K", d: 3.33 },
      { n: "KAT_Throw_O", d: 3.33 },
      { n: "KAT_Throw_P", d: 3.33 },
      { n: "PASS_Rifle_O", d: 1.33 },
      { n: "PASS_Rifle_Ped", d: 1.33 },
      { n: "PASS_Rifle_Ply", d: 1.33 },
      { n: "pickup_box", d: 0.4 },
      { n: "Plane_door", d: 5.33 },
      { n: "Plane_exit", d: 5.33 },
      { n: "Plane_hijack", d: 5.33 },
      { n: "Plunger_01", d: 3.33 },
      { n: "Plyrlean_loop", d: 2.67 },
      { n: "plyr_shkhead", d: 1.67 },
      { n: "Run_Dive", d: 8.27 },
      { n: "Scratchballs_01", d: 8.33 },
      { n: "SEAT_LR", d: 3.67 },
      { n: "Seat_talk_01", d: 3.67 },
      { n: "Seat_talk_02", d: 3.33 },
      { n: "SEAT_watch", d: 2.33 },
      { n: "smalplane_door", d: 6.33 },
      { n: "smlplane_door", d: 5.33 },
      { n: "MTB_back", d: 0.1 },
      { n: "MTB_bunnyhop", d: 0.33 },
      { n: "MTB_drivebyFT", d: 0.2 },
      { n: "MTB_driveby_LHS", d: 0.2 },
      { n: "MTB_driveby_RHS", d: 0.2 },
      { n: "MTB_fwd", d: 0.2 },
      { n: "MTB_getoffBACK", d: 1.53 },
      { n: "MTB_getoffLHS", d: 0.73 },
      { n: "MTB_getoffRHS", d: 0.73 },
      { n: "MTB_jumponL", d: 0.8 },
      { n: "MTB_jumponR", d: 0.83 },
      { n: "MTB_Left", d: 0.13 },
      { n: "MTB_pedal", d: 0.67 },
      { n: "MTB_pushes", d: 0.8 },
      { n: "MTB_Ride", d: 0.03 },
      { n: "MTB_Right", d: 0.13 },
      { n: "MTB_sprint", d: 0.8 },
      { n: "MTB_still", d: 0.03 },
      { n: "MscleWalkst_armed", d: 0.2 },
      { n: "MscleWalkst_Csaw", d: 0.2 },
      { n: "Mscle_rckt_run", d: 0.8 },
      { n: "Mscle_rckt_walkst", d: 0.2 },
      { n: "Mscle_run_Csaw", d: 0.8 },
      { n: "MuscleIdle", d: 1.5 },
      { n: "MuscleIdle_armed", d: 1.5 },
      { n: "MuscleIdle_Csaw", d: 1.5 },
      { n: "MuscleIdle_rocket", d: 1.5 },
      { n: "MuscleRun", d: 0.8 },
      { n: "MuscleRun_armed", d: 0.8 },
      { n: "MuscleSprint", d: 0.57 },
      { n: "MuscleWalk", d: 1.07 },
      { n: "MuscleWalkstart", d: 0.27 },
      { n: "MuscleWalk_armed", d: 1.07 },
      { n: "Musclewalk_Csaw", d: 1.07 },
      { n: "Musclewalk_rocket", d: 1.07 },
    ],
  ],
  [
    "NEVADA",
    [
      { n: "NEVADA_getin", d: 1.87 },
      { n: "NEVADA_getout", d: 0.93 },
    ],
  ],
  [
    "ON_LOOKERS",
    [
      { n: "lkaround_in", d: 0.33 },
      { n: "lkaround_loop", d: 7.0 },
      { n: "lkaround_out", d: 0.33 },
      { n: "lkup_in", d: 1.67 },
      { n: "lkup_loop", d: 5.33 },
      { n: "lkup_out", d: 1.0 },
      { n: "lkup_point", d: 3.33 },
      { n: "panic_cower", d: 6.67 },
      { n: "panic_hide", d: 6.33 },
      { n: "panic_in", d: 0.83 },
      { n: "panic_loop", d: 1.67 },
      { n: "panic_out", d: 0.67 },
      { n: "panic_point", d: 6.0 },
      { n: "panic_shout", d: 8.67 },
      { n: "Pointup_in", d: 1.0 },
      { n: "Pointup_loop", d: 2.67 },
      { n: "Pointup_out", d: 1.0 },
      { n: "Pointup_shout", d: 3.0 },
      { n: "point_in", d: 0.5 },
      { n: "point_loop", d: 3.0 },
      { n: "point_out", d: 0.33 },
      { n: "shout_01", d: 2.67 },
      { n: "shout_02", d: 4.0 },
      { n: "shout_in", d: 1.67 },
      { n: "shout_loop", d: 2.0 },
      { n: "shout_out", d: 0.33 },
      { n: "wave_in", d: 0.83 },
      { n: "wave_loop", d: 1.5 },
      { n: "wave_out", d: 0.83 },
    ],
  ],
  [
    "OTB",
    [
      { n: "betslp_in", d: 1.33 },
      { n: "betslp_lkabt", d: 2.67 },
      { n: "betslp_loop", d: 2.67 },
      { n: "betslp_out", d: 1.0 },
      { n: "betslp_tnk", d: 5.6 },
      { n: "wtchrace_cmon", d: 5.0 },
      { n: "wtchrace_in", d: 1.67 },
      { n: "wtchrace_loop", d: 2.67 },
      { n: "wtchrace_lose", d: 4.0 },
      { n: "wtchrace_out", d: 1.0 },
      { n: "wtchrace_win", d: 4.33 },
    ],
  ],
  [
    "PARACHUTE",
    [
      { n: "FALL_skyDive", d: 1.33 },
      { n: "FALL_SkyDive_Accel", d: 1.33 },
      { n: "FALL_skyDive_DIE", d: 1.0 },
      { n: "FALL_SkyDive_L", d: 1.33 },
      { n: "FALL_SkyDive_R", d: 1.33 },
      { n: "PARA_decel", d: 2.0 },
      { n: "PARA_decel_O", d: 2.0 },
      { n: "PARA_float", d: 2.0 },
      { n: "PARA_float_O", d: 2.0 },
      { n: "PARA_Land", d: 1.67 },
      { n: "PARA_Land_O", d: 2.17 },
      { n: "PARA_Land_Water", d: 2.33 },
      { n: "PARA_Land_Water_O", d: 2.17 },
      { n: "PARA_open", d: 2.83 },
      { n: "PARA_open_O", d: 2.33 },
      { n: "PARA_Rip_Land_O", d: 0.9 },
      { n: "PARA_Rip_Loop_O", d: 1.0 },
      { n: "PARA_Rip_O", d: 0.23 },
      { n: "PARA_steerL", d: 2.0 },
      { n: "PARA_steerL_O", d: 2.0 },
      { n: "PARA_steerR", d: 2.0 },
      { n: "PARA_steerR_O", d: 2.0 },
    ],
  ],
  [
    "PARK",
    [
      { n: "Tai_Chi_in", d: 2.17 },
      { n: "Tai_Chi_Loop", d: 12.0 },
      { n: "Tai_Chi_Out", d: 0.83 },
    ],
  ],
  [
    "PAULNMAC",
    [
      { n: "Piss_in", d: 9.0 },
      { n: "Piss_loop", d: 6.67 },
      { n: "Piss_out", d: 11.0 },
      { n: "PnM_Argue1_A", d: 4.33 },
      { n: "PnM_Argue1_B", d: 4.33 },
      { n: "PnM_Argue2_A", d: 4.33 },
      { n: "PnM_Argue2_B", d: 4.33 },
      { n: "PnM_Loop_A", d: 5.33 },
      { n: "PnM_Loop_B", d: 5.33 },
      { n: "wank_in", d: 7.33 },
      { n: "wank_loop", d: 2.67 },
      { n: "wank_out", d: 11.67 },
    ],
  ],
  [
    "ped",
    [
      { n: "abseil", d: 0.03 },
      { n: "ARRESTgun", d: 0.67 },
      { n: "ATM", d: 12.17 },
      { n: "BIKE_elbowL", d: 0.97 },
      { n: "BIKE_elbowR", d: 0.97 },
      { n: "BIKE_fallR", d: 1.63 },
      { n: "BIKE_fall_off", d: 1.07 },
      { n: "BIKE_pickupL", d: 1.07 },
      { n: "BIKE_pickupR", d: 1.07 },
      { n: "BIKE_pullupL", d: 1.0 },
      { n: "BIKE_pullupR", d: 1.0 },
      { n: "bomber", d: 0.6 },
      { n: "CAR_alignHI_LHS", d: 0.73 },
      { n: "CAR_alignHI_RHS", d: 0.73 },
      { n: "CAR_align_LHS", d: 0.13 },
      { n: "CAR_align_RHS", d: 0.13 },
      { n: "CAR_closedoorL_LHS", d: 0.6 },
      { n: "CAR_closedoorL_RHS", d: 0.4 },
      { n: "CAR_closedoor_LHS", d: 0.6 },
      { n: "CAR_closedoor_RHS", d: 0.4 },
      { n: "CAR_close_LHS", d: 0.73 },
      { n: "CAR_close_RHS", d: 0.73 },
      { n: "CAR_crawloutRHS", d: 2.17 },
      { n: "CAR_dead_LHS", d: 0.03 },
      { n: "CAR_dead_RHS", d: 0.03 },
      { n: "CAR_doorlocked_LHS", d: 1.33 },
      { n: "CAR_doorlocked_RHS", d: 1.27 },
      { n: "CAR_fallout_LHS", d: 0.57 },
      { n: "CAR_fallout_RHS", d: 0.57 },
      { n: "CAR_getinL_LHS", d: 1.0 },
      { n: "CAR_getinL_RHS", d: 1.0 },
      { n: "CAR_getin_LHS", d: 1.0 },
      { n: "CAR_getin_RHS", d: 1.0 },
      { n: "CAR_getoutL_LHS", d: 0.93 },
      { n: "CAR_getoutL_RHS", d: 1.0 },
      { n: "CAR_getout_LHS", d: 1.13 },
      { n: "CAR_getout_RHS", d: 0.8 },
      { n: "car_hookertalk", d: 4.3 },
      { n: "CAR_jackedLHS", d: 2.9 },
      { n: "CAR_jackedRHS", d: 3.43 },
      { n: "CAR_jumpin_LHS", d: 1.0 },
      { n: "CAR_LB", d: 0.23 },
      { n: "CAR_LB_pro", d: 0.1 },
      { n: "CAR_LB_weak", d: 0.23 },
      { n: "CAR_LjackedLHS", d: 3.57 },
      { n: "CAR_LjackedRHS", d: 3.47 },
      { n: "CAR_Lshuffle_RHS", d: 0.4 },
      { n: "CAR_Lsit", d: 0.03 },
      { n: "CAR_open_LHS", d: 1.1 },
      { n: "CAR_open_RHS", d: 1.1 },
      { n: "CAR_pulloutL_LHS", d: 2.93 },
      { n: "CAR_pulloutL_RHS", d: 2.93 },
      { n: "CAR_pullout_LHS", d: 2.3 },
      { n: "CAR_pullout_RHS", d: 2.8 },
      { n: "CAR_Qjacked", d: 3.3 },
      { n: "CAR_rolldoor", d: 0.6 },
      { n: "CAR_rolldoorLO", d: 0.6 },
      { n: "CAR_rollout_LHS", d: 1.63 },
      { n: "CAR_rollout_RHS", d: 1.27 },
      { n: "CAR_shuffle_RHS", d: 0.4 },
      { n: "CAR_sit", d: 0.03 },
      { n: "CAR_sitp", d: 0.03 },
      { n: "CAR_sitpLO", d: 0.03 },
      { n: "CAR_sit_pro", d: 0.03 },
      { n: "CAR_sit_weak", d: 0.03 },
      { n: "CAR_tune_radio", d: 0.63 },
      { n: "CLIMB_idle", d: 0.8 },
      { n: "CLIMB_jump", d: 0.57 },
      { n: "CLIMB_jump2fall", d: 0.03 },
      { n: "CLIMB_jump_B", d: 0.97 },
      { n: "CLIMB_Pull", d: 0.87 },
      { n: "CLIMB_Stand", d: 0.8 },
      { n: "CLIMB_Stand_finish", d: 0.2 },
      { n: "cower", d: 0.8 },
      { n: "Crouch_Roll_L", d: 0.93 },
      { n: "Crouch_Roll_R", d: 0.93 },
      { n: "DAM_armL_frmBK", d: 0.83 },
      { n: "DAM_armL_frmFT", d: 0.83 },
      { n: "DAM_armL_frmLT", d: 0.67 },
      { n: "DAM_armR_frmBK", d: 0.83 },
      { n: "DAM_armR_frmFT", d: 0.5 },
      { n: "DAM_armR_frmRT", d: 0.27 },
      { n: "DAM_LegL_frmBK", d: 0.83 },
      { n: "DAM_LegL_frmFT", d: 0.83 },
      { n: "DAM_LegL_frmLT", d: 0.83 },
      { n: "DAM_LegR_frmBK", d: 0.83 },
      { n: "DAM_LegR_frmFT", d: 0.83 },
      { n: "DAM_LegR_frmRT", d: 0.83 },
      { n: "DAM_stomach_frmBK", d: 0.83 },
      { n: "DAM_stomach_frmFT", d: 0.83 },
      { n: "DAM_stomach_frmLT", d: 0.83 },
      { n: "DAM_stomach_frmRT", d: 0.83 },
      { n: "DOOR_LHinge_O", d: 1.07 },
      { n: "DOOR_RHinge_O", d: 1.07 },
      { n: "DrivebyL_L", d: 0.2 },
      { n: "DrivebyL_R", d: 0.2 },
      { n: "Driveby_L", d: 0.2 },
      { n: "Driveby_R", d: 0.2 },
      { n: "DRIVE_BOAT", d: 0.03 },
      { n: "DRIVE_BOAT_back", d: 0.1 },
      { n: "DRIVE_BOAT_L", d: 0.1 },
      { n: "DRIVE_BOAT_R", d: 0.1 },
      { n: "Drive_L", d: 0.13 },
      { n: "Drive_LO_l", d: 0.13 },
      { n: "Drive_LO_R", d: 0.13 },
      { n: "Drive_L_pro", d: 0.13 },
      { n: "Drive_L_pro_slow", d: 0.13 },
      { n: "Drive_L_slow", d: 0.13 },
      { n: "Drive_L_weak", d: 0.13 },
      { n: "Drive_L_weak_slow", d: 0.13 },
      { n: "Drive_R", d: 0.13 },
      { n: "Drive_R_pro", d: 0.13 },
      { n: "Drive_R_pro_slow", d: 0.13 },
      { n: "Drive_R_slow", d: 0.13 },
      { n: "Drive_R_weak", d: 0.13 },
      { n: "Drive_R_weak_slow", d: 0.13 },
      { n: "Drive_truck", d: 0.03 },
      { n: "DRIVE_truck_back", d: 0.1 },
      { n: "DRIVE_truck_L", d: 0.13 },
      { n: "DRIVE_truck_R", d: 0.13 },
      { n: "Drown", d: 2.5 },
      { n: "DUCK_cower", d: 0.8 },
      { n: "endchat_01", d: 2.0 },
      { n: "endchat_02", d: 2.0 },
      { n: "endchat_03", d: 2.33 },
      { n: "EV_dive", d: 2.33 },
      { n: "EV_step", d: 1.07 },
      { n: "facanger", d: 0.13 },
      { n: "facgum", d: 1.03 },
      { n: "facsurp", d: 0.13 },
      { n: "facsurpm", d: 0.13 },
      { n: "factalk", d: 2.33 },
      { n: "facurios", d: 0.13 },
      { n: "FALL_back", d: 0.73 },
      { n: "FALL_collapse", d: 1.0 },
      { n: "FALL_fall", d: 0.73 },
      { n: "FALL_front", d: 0.73 },
      { n: "FALL_glide", d: 0.8 },
      { n: "FALL_land", d: 0.47 },
      { n: "FALL_skyDive", d: 1.33 },
      { n: "Fight2Idle", d: 0.33 },
      { n: "FightA_1", d: 0.43 },
      { n: "FightA_2", d: 0.77 },
      { n: "FightA_3", d: 0.87 },
      { n: "FightA_block", d: 0.47 },
      { n: "FightA_G", d: 0.93 },
      { n: "FightA_M", d: 0.4 },
      { n: "FIGHTIDLE", d: 1.3 },
      { n: "FightShB", d: 0.47 },
      { n: "FightShF", d: 0.53 },
      { n: "FightSh_BWD", d: 0.67 },
      { n: "FightSh_FWD", d: 0.67 },
      { n: "FightSh_Left", d: 0.67 },
      { n: "FightSh_Right", d: 0.67 },
      { n: "flee_lkaround_01", d: 2.0 },
      { n: "FLOOR_hit", d: 0.37 },
      { n: "FLOOR_hit_f", d: 0.4 },
      { n: "fucku", d: 1.33 },
      { n: "gang_gunstand", d: 0.03 },
      { n: "gas_cwr", d: 1.0 },
      { n: "getup", d: 1.37 },
      { n: "getup_front", d: 1.37 },
      { n: "gum_eat", d: 5.33 },
      { n: "GunCrouchBwd", d: 1.0 },
      { n: "GunCrouchFwd", d: 0.73 },
      { n: "GunMove_BWD", d: 1.03 },
      { n: "GunMove_FWD", d: 1.0 },
      { n: "GunMove_L", d: 1.0 },
      { n: "GunMove_R", d: 1.0 },
      { n: "Gun_2_IDLE", d: 0.27 },
      { n: "GUN_BUTT", d: 0.43 },
      { n: "GUN_BUTT_crouch", d: 0.43 },
      { n: "Gun_stand", d: 0.03 },
      { n: "handscower", d: 1.93 },
      { n: "handsup", d: 0.6 },
      { n: "HitA_1", d: 0.3 },
      { n: "HitA_2", d: 0.53 },
      { n: "HitA_3", d: 0.57 },
      { n: "HIT_back", d: 0.5 },
      { n: "HIT_behind", d: 0.67 },
      { n: "HIT_front", d: 0.6 },
      { n: "HIT_GUN_BUTT", d: 0.5 },
      { n: "HIT_L", d: 0.7 },
      { n: "HIT_R", d: 0.6 },
      { n: "HIT_walk", d: 0.33 },
      { n: "HIT_wall", d: 0.7 },
      { n: "Idlestance_fat", d: 1.67 },
      { n: "idlestance_old", d: 2.0 },
      { n: "IDLE_armed", d: 1.47 },
      { n: "IDLE_chat", d: 6.67 },
      { n: "IDLE_csaw", d: 1.53 },
      { n: "Idle_Gang1", d: 1.67 },
      { n: "IDLE_HBHB", d: 2.67 },
      { n: "IDLE_ROCKET", d: 1.57 },
      { n: "IDLE_stance", d: 1.5 },
      { n: "IDLE_taxi", d: 0.87 },
      { n: "IDLE_tired", d: 1.0 },
      { n: "Jetpack_Idle", d: 0.03 },
      { n: "JOG_femaleA", d: 0.77 },
      { n: "JOG_maleA", d: 0.77 },
      { n: "JUMP_glide", d: 0.5 },
      { n: "JUMP_land", d: 0.23 },
      { n: "JUMP_launch", d: 0.2 },
      { n: "JUMP_launch_R", d: 0.2 },
      { n: "KART_drive", d: 0.03 },
      { n: "KART_L", d: 0.13 },
      { n: "KART_LB", d: 0.03 },
      { n: "KART_R", d: 0.13 },
      { n: "KD_left", d: 0.9 },
      { n: "KD_right", d: 0.9 },
      { n: "KO_shot_face", d: 2.1 },
      { n: "KO_shot_front", d: 0.57 },
      { n: "KO_shot_stom", d: 3.17 },
      { n: "KO_skid_back", d: 0.97 },
      { n: "KO_skid_front", d: 1.13 },
      { n: "KO_spin_L", d: 0.87 },
      { n: "KO_spin_R", d: 0.93 },
      { n: "pass_Smoke_in_car", d: 1.73 },
      { n: "phone_in", d: 2.33 },
      { n: "phone_out", d: 2.0 },
      { n: "phone_talk", d: 2.0 },
      { n: "Player_Sneak", d: 1.33 },
      { n: "Player_Sneak_walkstart", d: 0.3 },
      { n: "roadcross", d: 2.0 },
      { n: "roadcross_female", d: 4.0 },
      { n: "roadcross_gang", d: 2.0 },
      { n: "roadcross_old", d: 4.0 },
      { n: "run_1armed", d: 0.77 },
      { n: "run_armed", d: 0.7 },
      { n: "run_civi", d: 0.73 },
      { n: "run_csaw", d: 0.7 },
      { n: "run_fat", d: 0.8 },
      { n: "run_fatold", d: 0.8 },
      { n: "run_gang1", d: 0.83 },
      { n: "run_left", d: 0.67 },
      { n: "run_old", d: 0.8 },
      { n: "run_player", d: 0.73 },
      { n: "run_right", d: 0.67 },
      { n: "run_rocket", d: 0.77 },
      { n: "Run_stop", d: 0.87 },
      { n: "Run_stopR", d: 0.8 },
      { n: "Run_Wuzi", d: 0.77 },
      { n: "SEAT_down", d: 1.5 },
      { n: "SEAT_idle", d: 2.0 },
      { n: "SEAT_up", d: 1.17 },
      { n: "SHOT_leftP", d: 0.3 },
      { n: "SHOT_partial", d: 0.37 },
      { n: "SHOT_partial_B", d: 0.33 },
      { n: "SHOT_rightP", d: 0.33 },
      { n: "Shove_Partial", d: 0.53 },
      { n: "Smoke_in_car", d: 1.73 },
      { n: "sprint_civi", d: 0.53 },
      { n: "sprint_panic", d: 0.6 },
      { n: "Sprint_Wuzi", d: 0.67 },
      { n: "swat_run", d: 0.67 },
      { n: "Swim_Tread", d: 1.3 },
      { n: "Tap_hand", d: 0.03 },
      { n: "Tap_handP", d: 0.03 },
      { n: "turn_180", d: 0.63 },
      { n: "Turn_L", d: 0.8 },
      { n: "Turn_R", d: 0.8 },
      { n: "WALK_armed", d: 1.07 },
      { n: "WALK_civi", d: 1.13 },
      { n: "WALK_csaw", d: 1.07 },
      { n: "Walk_DoorPartial", d: 0.8 },
      { n: "WALK_drunk", d: 3.93 },
      { n: "WALK_fat", d: 1.33 },
      { n: "WALK_fatold", d: 1.17 },
      { n: "WALK_gang1", d: 1.4 },
      { n: "WALK_gang2", d: 1.4 },
      { n: "WALK_old", d: 1.4 },
      { n: "WALK_player", d: 1.2 },
      { n: "WALK_rocket", d: 1.07 },
      { n: "WALK_shuffle", d: 1.2 },
      { n: "WALK_start", d: 0.27 },
      { n: "WALK_start_armed", d: 0.2 },
      { n: "WALK_start_csaw", d: 0.2 },
      { n: "WALK_start_rocket", d: 0.2 },
      { n: "Walk_Wuzi", d: 1.17 },
      { n: "WEAPON_crouch", d: 0.8 },
      { n: "woman_idlestance", d: 5.33 },
      { n: "woman_run", d: 0.77 },
      { n: "WOMAN_runbusy", d: 0.67 },
      { n: "WOMAN_runfatold", d: 1.2 },
      { n: "woman_runpanic", d: 0.6 },
      { n: "WOMAN_runsexy", d: 0.7 },
      { n: "WOMAN_walkbusy", d: 1.0 },
      { n: "WOMAN_walkfatold", d: 1.2 },
      { n: "WOMAN_walknorm", d: 1.13 },
      { n: "WOMAN_walkold", d: 1.2 },
      { n: "WOMAN_walkpro", d: 1.33 },
      { n: "WOMAN_walksexy", d: 1.17 },
      { n: "WOMAN_walkshop", d: 0.97 },
      { n: "XPRESSscratch", d: 3.97 },
    ],
  ],
  [
    "PLAYER_DVBYS",
    [
      { n: "Plyr_DrivebyBwd", d: 0.83 },
      { n: "Plyr_DrivebyFwd", d: 0.83 },
      { n: "Plyr_DrivebyLHS", d: 0.83 },
      { n: "Plyr_DrivebyRHS", d: 0.83 },
    ],
  ],
  [
    "PLAYIDLES",
    [
      { n: "shift", d: 3.6 },
      { n: "shldr", d: 2.17 },
      { n: "stretch", d: 4.6 },
      { n: "strleg", d: 3.67 },
      { n: "time", d: 5.2 },
    ],
  ],
  [
    "POLICE",
    [
      { n: "CopTraf_Away", d: 1.47 },
      { n: "CopTraf_Come", d: 2.87 },
      { n: "CopTraf_Left", d: 2.0 },
      { n: "CopTraf_Stop", d: 2.0 },
      { n: "COP_getoutcar_LHS", d: 0.83 },
      { n: "Cop_move_FWD", d: 1.0 },
      { n: "crm_drgbst_01", d: 18.57 },
      { n: "Door_Kick", d: 1.33 },
      { n: "plc_drgbst_01", d: 20.6 },
      { n: "plc_drgbst_02", d: 7.57 },
    ],
  ],
  [
    "POOL",
    [
      { n: "POOL_ChalkCue", d: 4.83 },
      { n: "POOL_Idle_Stance", d: 2.0 },
      { n: "POOL_Long_Shot", d: 1.67 },
      { n: "POOL_Long_Shot_O", d: 1.67 },
      { n: "POOL_Long_Start", d: 0.67 },
      { n: "POOL_Long_Start_O", d: 0.67 },
      { n: "POOL_Med_Shot", d: 1.67 },
      { n: "POOL_Med_Shot_O", d: 1.67 },
      { n: "POOL_Med_Start", d: 0.67 },
      { n: "POOL_Med_Start_O", d: 0.67 },
      { n: "POOL_Place_White", d: 2.5 },
      { n: "POOL_Short_Shot", d: 1.67 },
      { n: "POOL_Short_Shot_O", d: 1.67 },
      { n: "POOL_Short_Start", d: 0.67 },
      { n: "POOL_Short_Start_O", d: 0.67 },
      { n: "POOL_Walk", d: 1.27 },
      { n: "POOL_Walk_Start", d: 0.2 },
      { n: "POOL_XLong_Shot", d: 1.67 },
      { n: "POOL_XLong_Shot_O", d: 1.67 },
      { n: "POOL_XLong_Start", d: 0.67 },
      { n: "POOL_XLong_Start_O", d: 0.67 },
    ],
  ],
  [
    "POOR",
    [
      { n: "WINWASH_Start", d: 0.43 },
      { n: "WINWASH_Wash2Beg", d: 2.13 },
    ],
  ],
  [
    "PYTHON",
    [
      { n: "python_crouchfire", d: 1.2 },
      { n: "python_crouchreload", d: 1.0 },
      { n: "python_fire", d: 1.17 },
      { n: "python_fire_poor", d: 1.47 },
      { n: "python_reload", d: 0.93 },
    ],
  ],
  [
    "QUAD",
    [
      { n: "QUAD_back", d: 0.1 },
      { n: "QUAD_driveby_FT", d: 0.2 },
      { n: "QUAD_driveby_LHS", d: 0.2 },
      { n: "QUAD_driveby_RHS", d: 0.2 },
      { n: "QUAD_FWD", d: 0.2 },
      { n: "QUAD_getoff_B", d: 1.63 },
      { n: "QUAD_getoff_LHS", d: 0.67 },
      { n: "QUAD_getoff_RHS", d: 0.7 },
      { n: "QUAD_geton_LHS", d: 0.73 },
      { n: "QUAD_geton_RHS", d: 0.73 },
      { n: "QUAD_hit", d: 0.03 },
      { n: "QUAD_kick", d: 1.13 },
      { n: "QUAD_Left", d: 0.13 },
      { n: "QUAD_passenger", d: 0.03 },
      { n: "QUAD_reverse", d: 0.17 },
      { n: "QUAD_ride", d: 0.03 },
      { n: "QUAD_Right", d: 0.13 },
    ],
  ],
  [
    "QUAD_DBZ",
    [
      { n: "Pass_Driveby_BWD", d: 0.83 },
      { n: "Pass_Driveby_FWD", d: 0.83 },
      { n: "Pass_Driveby_LHS", d: 0.83 },
      { n: "Pass_Driveby_RHS", d: 0.83 },
    ],
  ],
  [
    "RAPPING",
    [
      { n: "Laugh_01", d: 5.33 },
      { n: "RAP_A_IN", d: 0.83 },
      { n: "RAP_A_Loop", d: 2.67 },
      { n: "RAP_A_OUT", d: 0.33 },
      { n: "RAP_B_IN", d: 1.0 },
      { n: "RAP_B_Loop", d: 2.67 },
      { n: "RAP_B_OUT", d: 0.87 },
      { n: "RAP_C_Loop", d: 3.0 },
    ],
  ],
  [
    "RIFLE",
    [
      { n: "RIFLE_crouchfire", d: 0.87 },
      { n: "RIFLE_crouchload", d: 1.27 },
      { n: "RIFLE_fire", d: 0.8 },
      { n: "RIFLE_fire_poor", d: 0.8 },
      { n: "RIFLE_load", d: 1.4 },
    ],
  ],
  [
    "RIOT",
    [
      { n: "RIOT_ANGRY", d: 5.0 },
      { n: "RIOT_ANGRY_B", d: 0.63 },
      { n: "RIOT_challenge", d: 3.23 },
      { n: "RIOT_CHANT", d: 1.73 },
      { n: "RIOT_FUKU", d: 0.67 },
      { n: "RIOT_PUNCHES", d: 0.67 },
      { n: "RIOT_shout", d: 1.0 },
    ],
  ],
  [
    "ROB_BANK",
    [
      { n: "CAT_Safe_End", d: 0.5 },
      { n: "CAT_Safe_Open", d: 3.33 },
      { n: "CAT_Safe_Open_O", d: 3.33 },
      { n: "CAT_Safe_Rob", d: 1.83 },
      { n: "SHP_HandsUp_Scr", d: 0.67 },
    ],
  ],
  [
    "ROCKET",
    [
      { n: "idle_rocket", d: 1.6 },
      { n: "RocketFire", d: 0.97 },
      { n: "run_rocket", d: 0.77 },
      { n: "walk_rocket", d: 1.07 },
      { n: "WALK_start_rocket", d: 0.2 },
    ],
  ],
  [
    "RUNNINGMAN",
    [
      { n: "Dance_B1", d: 0.53 },
      { n: "Dance_B2", d: 0.57 },
      { n: "Dance_B3", d: 0.53 },
      { n: "Dance_B4", d: 0.57 },
      { n: "Dance_B5", d: 0.53 },
      { n: "Dance_B6", d: 0.57 },
      { n: "Dance_B7", d: 0.53 },
      { n: "Dance_B8", d: 0.57 },
      { n: "Dance_B9", d: 0.53 },
      { n: "Dance_B10", d: 0.57 },
      { n: "Dance_B11", d: 0.53 },
      { n: "Dance_B12", d: 0.57 },
      { n: "Dance_B13", d: 0.53 },
      { n: "Dance_B14", d: 0.57 },
      { n: "Dance_B15", d: 0.53 },
      { n: "Dance_B16", d: 0.57 },
      { n: "Dance_G1", d: 0.53 },
      { n: "Dance_G2", d: 0.57 },
      { n: "Dance_G3", d: 0.53 },
      { n: "Dance_G4", d: 0.57 },
      { n: "Dance_G5", d: 0.53 },
      { n: "Dance_G6", d: 0.57 },
      { n: "Dance_G7", d: 0.53 },
      { n: "Dance_G8", d: 0.57 },
      { n: "Dance_G9", d: 0.53 },
      { n: "Dance_G10", d: 0.57 },
      { n: "Dance_G11", d: 0.53 },
      { n: "Dance_G12", d: 0.57 },
      { n: "Dance_G13", d: 0.53 },
      { n: "Dance_G14", d: 0.57 },
      { n: "Dance_G15", d: 0.53 },
      { n: "Dance_G16", d: 0.57 },
      { n: "dance_loop", d: 1.17 },
    ],
  ],
  [
    "RUSTLER",
    [
      { n: "Plane_align_LHS", d: 0.73 },
      { n: "Plane_close", d: 0.4 },
      { n: "Plane_getin", d: 0.8 },
      { n: "Plane_getout", d: 1.57 },
      { n: "Plane_open", d: 0.7 },
    ],
  ],
  [
    "RYDER",
    [
      { n: "RYD_Beckon_01", d: 1.23 },
      { n: "RYD_Beckon_02", d: 1.0 },
      { n: "RYD_Beckon_03", d: 1.07 },
      { n: "RYD_Die_PT1", d: 4.0 },
      { n: "RYD_Die_PT2", d: 7.93 },
      { n: "Van_Crate_L", d: 0.67 },
      { n: "Van_Crate_R", d: 0.67 },
      { n: "Van_Fall_L", d: 0.47 },
      { n: "Van_Fall_R", d: 0.93 },
      { n: "Van_Lean_L", d: 0.67 },
      { n: "Van_Lean_R", d: 0.67 },
      { n: "VAN_PickUp_E", d: 1.83 },
      { n: "VAN_PickUp_S", d: 1.5 },
      { n: "Van_Stand", d: 0.67 },
      { n: "Van_Stand_Crate", d: 0.67 },
      { n: "Van_Throw", d: 1.37 },
    ],
  ],
  ["SAMP", [{ n: "FishingIdle", d: 1 }]],
  [
    "SCRATCHING",
    [
      { n: "scdldlp", d: 0.67 },
      { n: "scdlulp", d: 0.67 },
      { n: "scdrdlp", d: 0.67 },
      { n: "scdrulp", d: 0.67 },
      { n: "sclng_l", d: 1.0 },
      { n: "sclng_r", d: 1.0 },
      { n: "scmid_l", d: 0.47 },
      { n: "scmid_r", d: 0.47 },
      { n: "scshrtl", d: 0.2 },
      { n: "scshrtr", d: 0.2 },
      { n: "sc_ltor", d: 0.67 },
      { n: "sc_rtol", d: 0.67 },
    ],
  ],
  [
    "SHAMAL",
    [
      { n: "SHAMAL_align", d: 0.2 },
      { n: "SHAMAL_getin_LHS", d: 1.4 },
      { n: "SHAMAL_getout_LHS", d: 1.37 },
      { n: "SHAMAL_open", d: 0.6 },
    ],
  ],
  [
    "SHOP",
    [
      { n: "ROB_2Idle", d: 1.17 },
      { n: "ROB_Loop", d: 2.67 },
      { n: "ROB_Loop_Threat", d: 2.0 },
      { n: "ROB_Shifty", d: 5.67 },
      { n: "ROB_StickUp_In", d: 0.53 },
      { n: "SHP_Duck", d: 0.67 },
      { n: "SHP_Duck_Aim", d: 0.33 },
      { n: "SHP_Duck_Fire", d: 0.83 },
      { n: "SHP_Gun_Aim", d: 0.63 },
      { n: "SHP_Gun_Duck", d: 0.5 },
      { n: "SHP_Gun_Fire", d: 0.87 },
      { n: "SHP_Gun_Grab", d: 0.87 },
      { n: "SHP_Gun_Threat", d: 0.83 },
      { n: "SHP_HandsUp_Scr", d: 0.67 },
      { n: "SHP_Jump_Glide", d: 0.33 },
      { n: "SHP_Jump_Land", d: 0.7 },
      { n: "SHP_Jump_Launch", d: 0.57 },
      { n: "SHP_Rob_GiveCash", d: 3.83 },
      { n: "SHP_Rob_HandsUp", d: 2.67 },
      { n: "SHP_Rob_React", d: 2.67 },
      { n: "SHP_Serve_End", d: 5.5 },
      { n: "SHP_Serve_Idle", d: 5.0 },
      { n: "SHP_Serve_Loop", d: 4.17 },
      { n: "SHP_Serve_Start", d: 1.33 },
      { n: "Smoke_RYD", d: 6.67 },
    ],
  ],
  [
    "SHOTGUN",
    [
      { n: "shotgun_crouchfire", d: 1.47 },
      { n: "shotgun_fire", d: 1.47 },
      { n: "shotgun_fire_poor", d: 1.5 },
    ],
  ],
  [
    "SILENCED",
    [
      { n: "CrouchReload", d: 1.0 },
      { n: "SilenceCrouchfire", d: 0.93 },
      { n: "Silence_fire", d: 0.87 },
      { n: "Silence_reload", d: 0.93 },
    ],
  ],
  [
    "SKATE",
    [
      { n: "skate_idle", d: 1.0 },
      { n: "skate_run", d: 0.83 },
      { n: "skate_sprint", d: 0.67 },
    ],
  ],
  [
    "SMOKING",
    [
      { n: "F_smklean_loop", d: 4.0 },
      { n: "M_smklean_loop", d: 5.0 },
      { n: "M_smkstnd_loop", d: 5.33 },
      { n: "M_smk_drag", d: 3.67 },
      { n: "M_smk_in", d: 6.67 },
      { n: "M_smk_loop", d: 3.33 },
      { n: "M_smk_out", d: 3.0 },
      { n: "M_smk_tap", d: 3.0 },
    ],
  ],
  ["SNIPER", [{ n: "WEAPON_sniper", d: 1.47 }]],
  [
    "SnM",
    [
      { n: "SnM_Caned_Idle_P", d: 2.0 },
      { n: "SnM_Caned_Idle_W", d: 2.0 },
      { n: "SnM_Caned_P", d: 1.33 },
      { n: "SnM_Caned_W", d: 1.33 },
      { n: "SnM_Cane_Idle_P", d: 2.0 },
      { n: "SnM_Cane_Idle_W", d: 2.0 },
      { n: "SnM_Cane_P", d: 1.33 },
      { n: "SnM_Cane_W", d: 1.33 },
      { n: "SpankedP", d: 1.33 },
      { n: "SpankedW", d: 1.33 },
      { n: "Spanked_IdleP", d: 1.33 },
      { n: "Spanked_IdleW", d: 1.33 },
      { n: "SpankingP", d: 1.33 },
      { n: "SpankingW", d: 1.33 },
      { n: "Spanking_endP", d: 6.67 },
      { n: "Spanking_endW", d: 6.67 },
      { n: "Spanking_IdleP", d: 1.33 },
      { n: "Spanking_IdleW", d: 1.33 },
      { n: "Spanking_SittingIdleP", d: 1.33 },
      { n: "Spanking_SittingIdleW", d: 1.33 },
      { n: "Spanking_SittingP", d: 1.0 },
      { n: "Spanking_SittingW", d: 1.0 },
    ],
  ],
  [
    "SPRAYCAN",
    [
      { n: "spraycan_fire", d: 2.33 },
      { n: "spraycan_full", d: 4.5 },
    ],
  ],
  [
    "STRIP",
    [
      { n: "PLY_CASH", d: 1.67 },
      { n: "PUN_CASH", d: 3.33 },
      { n: "PUN_HOLLER", d: 5.0 },
      { n: "PUN_LOOP", d: 1.93 },
      { n: "strip_A", d: 2.07 },
      { n: "strip_B", d: 1.0 },
      { n: "strip_C", d: 0.97 },
      { n: "strip_D", d: 1.9 },
      { n: "strip_E", d: 3.33 },
      { n: "strip_F", d: 1.03 },
      { n: "strip_G", d: 2.27 },
      { n: "STR_A2B", d: 4.0 },
      { n: "STR_B2A", d: 0.5 },
      { n: "STR_B2C", d: 5.0 },
      { n: "STR_C1", d: 6.0 },
      { n: "STR_C2", d: 6.0 },
      { n: "STR_C2B", d: 1.0 },
      { n: "STR_Loop_A", d: 1.0 },
      { n: "STR_Loop_B", d: 2.0 },
      { n: "STR_Loop_C", d: 3.0 },
    ],
  ],
  [
    "SUNBATHE",
    [
      { n: "batherdown", d: 3.93 },
      { n: "batherup", d: 12.3 },
      { n: "Lay_Bac_in", d: 2.33 },
      { n: "Lay_Bac_out", d: 3.0 },
      { n: "ParkSit_M_IdleA", d: 3.33 },
      { n: "ParkSit_M_IdleB", d: 2.67 },
      { n: "ParkSit_M_IdleC", d: 4.33 },
      { n: "ParkSit_M_in", d: 2.33 },
      { n: "ParkSit_M_out", d: 2.0 },
      { n: "ParkSit_W_idleA", d: 3.33 },
      { n: "ParkSit_W_idleB", d: 5.0 },
      { n: "ParkSit_W_idleC", d: 3.0 },
      { n: "ParkSit_W_in", d: 4.0 },
      { n: "ParkSit_W_out", d: 2.67 },
      { n: "SBATHE_F_LieB2Sit", d: 1.67 },
      { n: "SBATHE_F_Out", d: 2.0 },
      { n: "SitnWait_in_W", d: 4.67 },
      { n: "SitnWait_out_W", d: 2.67 },
    ],
  ],
  [
    "SWAT",
    [
      { n: "gnstwall_injurd", d: 2.0 },
      { n: "JMP_Wall1m_180", d: 1.17 },
      { n: "Rail_fall", d: 3.0 },
      { n: "Rail_fall_crawl", d: 5.67 },
      { n: "swt_breach_01", d: 5.47 },
      { n: "swt_breach_02", d: 5.33 },
      { n: "swt_breach_03", d: 4.3 },
      { n: "swt_go", d: 1.67 },
      { n: "swt_lkt", d: 3.0 },
      { n: "swt_sty", d: 1.17 },
      { n: "swt_vent_01", d: 4.73 },
      { n: "swt_vent_02", d: 4.43 },
      { n: "swt_vnt_sht_die", d: 0.67 },
      { n: "swt_vnt_sht_in", d: 1.6 },
      { n: "swt_vnt_sht_loop", d: 0.27 },
      { n: "swt_wllpk_L", d: 2.67 },
      { n: "swt_wllpk_L_back", d: 0.5 },
      { n: "swt_wllpk_R", d: 3.67 },
      { n: "swt_wllpk_R_back", d: 0.43 },
      { n: "swt_wllshoot_in_L", d: 1.0 },
      { n: "swt_wllshoot_in_R", d: 1.3 },
      { n: "swt_wllshoot_out_L", d: 2.0 },
      { n: "swt_wllshoot_out_R", d: 1.43 },
    ],
  ],
  [
    "SWEET",
    [
      { n: "ho_ass_slapped", d: 2.0 },
      { n: "LaFin_Player", d: 26.67 },
      { n: "LaFin_Sweet", d: 26.67 },
      { n: "plyr_hndshldr_01", d: 4.0 },
      { n: "sweet_ass_slap", d: 2.0 },
      { n: "sweet_hndshldr_01", d: 4.0 },
      { n: "Sweet_injuredloop", d: 2.0 },
    ],
  ],
  [
    "SWIM",
    [
      { n: "Swim_Breast", d: 1.3 },
      { n: "SWIM_crawl", d: 0.9 },
      { n: "Swim_Dive_Under", d: 1.07 },
      { n: "Swim_Glide", d: 1.47 },
      { n: "Swim_jumpout", d: 0.33 },
      { n: "Swim_Tread", d: 1.3 },
      { n: "Swim_Under", d: 1.5 },
    ],
  ],
  [
    "SWORD",
    [
      { n: "sword_1", d: 0.87 },
      { n: "sword_2", d: 1.07 },
      { n: "sword_3", d: 0.8 },
      { n: "sword_4", d: 1.1 },
      { n: "sword_block", d: 0.47 },
      { n: "Sword_Hit_1", d: 0.83 },
      { n: "Sword_Hit_2", d: 1.03 },
      { n: "Sword_Hit_3", d: 0.87 },
      { n: "sword_IDLE", d: 1.0 },
      { n: "sword_part", d: 0.67 },
    ],
  ],
  [
    "TANK",
    [
      { n: "TANK_align_LHS", d: 1.43 },
      { n: "TANK_close_LHS", d: 0.33 },
      { n: "TANK_doorlocked", d: 0.53 },
      { n: "TANK_getin_LHS", d: 0.43 },
      { n: "TANK_getout_LHS", d: 1.97 },
      { n: "TANK_open_LHS", d: 0.3 },
    ],
  ],
  [
    "TATTOOS",
    [
      { n: "TAT_ArmL_In_O", d: 0.83 },
      { n: "TAT_ArmL_In_P", d: 0.83 },
      { n: "TAT_ArmL_In_T", d: 0.83 },
      { n: "TAT_ArmL_Out_O", d: 0.93 },
      { n: "TAT_ArmL_Out_P", d: 2.5 },
      { n: "TAT_ArmL_Out_T", d: 0.93 },
      { n: "TAT_ArmL_Pose_O", d: 0.83 },
      { n: "TAT_ArmL_Pose_P", d: 0.83 },
      { n: "TAT_ArmL_Pose_T", d: 0.83 },
      { n: "TAT_ArmR_In_O", d: 0.83 },
      { n: "TAT_ArmR_In_P", d: 0.83 },
      { n: "TAT_ArmR_In_T", d: 0.83 },
      { n: "TAT_ArmR_Out_O", d: 1.0 },
      { n: "TAT_ArmR_Out_P", d: 2.5 },
      { n: "TAT_ArmR_Out_T", d: 1.0 },
      { n: "TAT_ArmR_Pose_O", d: 0.83 },
      { n: "TAT_ArmR_Pose_P", d: 0.83 },
      { n: "TAT_ArmR_Pose_T", d: 0.83 },
      { n: "TAT_Back_In_O", d: 0.83 },
      { n: "TAT_Back_In_P", d: 0.83 },
      { n: "TAT_Back_In_T", d: 0.83 },
      { n: "TAT_Back_Out_O", d: 0.93 },
      { n: "TAT_Back_Out_P", d: 2.5 },
      { n: "TAT_Back_Out_T", d: 0.93 },
      { n: "TAT_Back_Pose_O", d: 0.83 },
      { n: "TAT_Back_Pose_P", d: 0.83 },
      { n: "TAT_Back_Pose_T", d: 0.83 },
      { n: "TAT_Back_Sit_In_P", d: 0.83 },
      { n: "TAT_Back_Sit_Loop_P", d: 2.67 },
      { n: "TAT_Back_Sit_Out_P", d: 0.83 },
      { n: "TAT_Bel_In_O", d: 0.83 },
      { n: "TAT_Bel_In_T", d: 0.83 },
      { n: "TAT_Bel_Out_O", d: 0.97 },
      { n: "TAT_Bel_Out_T", d: 0.97 },
      { n: "TAT_Bel_Pose_O", d: 0.83 },
      { n: "TAT_Bel_Pose_T", d: 0.83 },
      { n: "TAT_Che_In_O", d: 0.83 },
      { n: "TAT_Che_In_P", d: 0.83 },
      { n: "TAT_Che_In_T", d: 0.83 },
      { n: "TAT_Che_Out_O", d: 0.93 },
      { n: "TAT_Che_Out_P", d: 2.5 },
      { n: "TAT_Che_Out_T", d: 0.93 },
      { n: "TAT_Che_Pose_O", d: 0.83 },
      { n: "TAT_Che_Pose_P", d: 0.83 },
      { n: "TAT_Che_Pose_T", d: 0.83 },
      { n: "TAT_Drop_O", d: 0.5 },
      { n: "TAT_Idle_Loop_O", d: 2.67 },
      { n: "TAT_Idle_Loop_T", d: 2.67 },
      { n: "TAT_Sit_In_O", d: 2.33 },
      { n: "TAT_Sit_In_P", d: 2.33 },
      { n: "TAT_Sit_In_T", d: 2.33 },
      { n: "TAT_Sit_Loop_O", d: 2.67 },
      { n: "TAT_Sit_Loop_P", d: 2.67 },
      { n: "TAT_Sit_Loop_T", d: 2.67 },
      { n: "TAT_Sit_Out_O", d: 2.83 },
      { n: "TAT_Sit_Out_P", d: 2.17 },
      { n: "TAT_Sit_Out_T", d: 2.83 },
    ],
  ],
  [
    "TEC",
    [
      { n: "TEC_crouchfire", d: 0.97 },
      { n: "TEC_crouchreload", d: 1.33 },
      { n: "TEC_fire", d: 1.1 },
      { n: "TEC_reload", d: 1.5 },
    ],
  ],
  [
    "TRAIN",
    [
      { n: "tran_gtup", d: 3.17 },
      { n: "tran_hng", d: 2.33 },
      { n: "tran_ouch", d: 1.17 },
      { n: "tran_stmb", d: 2.33 },
    ],
  ],
  [
    "TRUCK",
    [
      { n: "TRUCK_ALIGN_LHS", d: 0.57 },
      { n: "TRUCK_ALIGN_RHS", d: 0.57 },
      { n: "TRUCK_closedoor_LHS", d: 0.4 },
      { n: "TRUCK_closedoor_RHS", d: 0.4 },
      { n: "TRUCK_close_LHS", d: 0.73 },
      { n: "TRUCK_close_RHS", d: 0.73 },
      { n: "TRUCK_getin_LHS", d: 0.6 },
      { n: "TRUCK_getin_RHS", d: 0.6 },
      { n: "TRUCK_getout_LHS", d: 0.8 },
      { n: "TRUCK_getout_RHS", d: 0.8 },
      { n: "TRUCK_jackedLHS", d: 1.73 },
      { n: "TRUCK_jackedRHS", d: 1.5 },
      { n: "TRUCK_open_LHS", d: 0.53 },
      { n: "TRUCK_open_RHS", d: 0.53 },
      { n: "TRUCK_pullout_LHS", d: 0.9 },
      { n: "TRUCK_pullout_RHS", d: 0.9 },
      { n: "TRUCK_Shuffle", d: 0.4 },
    ],
  ],
  [
    "UZI",
    [
      { n: "UZI_crouchfire", d: 0.63 },
      { n: "UZI_crouchreload", d: 1.37 },
      { n: "UZI_fire", d: 0.57 },
      { n: "UZI_fire_poor", d: 0.53 },
      { n: "UZI_reload", d: 1.4 },
    ],
  ],
  [
    "VAN",
    [
      { n: "VAN_close_back_LHS", d: 0.33 },
      { n: "VAN_close_back_RHS", d: 0.33 },
      { n: "VAN_getin_Back_LHS", d: 0.6 },
      { n: "VAN_getin_Back_RHS", d: 0.6 },
      { n: "VAN_getout_back_LHS", d: 0.63 },
      { n: "VAN_getout_back_RHS", d: 0.63 },
      { n: "VAN_open_back_LHS", d: 0.97 },
      { n: "VAN_open_back_RHS", d: 0.97 },
    ],
  ],
  [
    "VENDING",
    [
      { n: "VEND_Drink2_P", d: 3.33 },
      { n: "VEND_Drink_P", d: 1.33 },
      { n: "vend_eat1_P", d: 4.33 },
      { n: "VEND_Eat_P", d: 1.67 },
      { n: "VEND_Use", d: 2.6 },
      { n: "VEND_Use_pt2", d: 0.4 },
    ],
  ],
  [
    "VORTEX",
    [
      { n: "CAR_jumpin_LHS", d: 1.0 },
      { n: "CAR_jumpin_RHS", d: 0.93 },
      { n: "vortex_getout_LHS", d: 1.0 },
      { n: "vortex_getout_RHS", d: 1.0 },
    ],
  ],
  [
    "WAYFARER",
    [
      { n: "WF_Back", d: 0.1 },
      { n: "WF_drivebyFT", d: 0.2 },
      { n: "WF_drivebyLHS", d: 0.2 },
      { n: "WF_drivebyRHS", d: 0.2 },
      { n: "WF_Fwd", d: 0.2 },
      { n: "WF_getoffBACK", d: 1.73 },
      { n: "WF_getoffLHS", d: 0.9 },
      { n: "WF_getoffRHS", d: 0.9 },
      { n: "WF_hit", d: 0.03 },
      { n: "WF_jumponL", d: 0.9 },
      { n: "WF_jumponR", d: 0.9 },
      { n: "WF_kick", d: 1.03 },
      { n: "WF_Left", d: 0.13 },
      { n: "WF_passenger", d: 0.03 },
      { n: "WF_pushes", d: 0.97 },
      { n: "WF_Ride", d: 0.03 },
      { n: "WF_Right", d: 0.13 },
      { n: "WF_Still", d: 0.03 },
    ],
  ],
  [
    "WEAPONS",
    [
      { n: "SHP_1H_Lift", d: 1.0 },
      { n: "SHP_1H_Lift_End", d: 0.33 },
      { n: "SHP_1H_Ret", d: 0.83 },
      { n: "SHP_1H_Ret_S", d: 0.33 },
      { n: "SHP_2H_Lift", d: 0.93 },
      { n: "SHP_2H_Lift_End", d: 0.33 },
      { n: "SHP_2H_Ret", d: 0.9 },
      { n: "SHP_2H_Ret_S", d: 0.33 },
      { n: "SHP_Ar_Lift", d: 1.0 },
      { n: "SHP_Ar_Lift_End", d: 0.33 },
      { n: "SHP_Ar_Ret", d: 1.17 },
      { n: "SHP_Ar_Ret_S", d: 0.33 },
      { n: "SHP_G_Lift_In", d: 0.67 },
      { n: "SHP_G_Lift_Out", d: 0.67 },
      { n: "SHP_Tray_In", d: 0.67 },
      { n: "SHP_Tray_Out", d: 0.67 },
      { n: "SHP_Tray_Pose", d: 2.67 },
    ],
  ],
  [
    "WOP",
    [
      { n: "Dance_B1", d: 1.13 },
      { n: "Dance_B2", d: 1.17 },
      { n: "Dance_B3", d: 1.13 },
      { n: "Dance_B4", d: 1.17 },
      { n: "Dance_B5", d: 1.13 },
      { n: "Dance_B6", d: 1.17 },
      { n: "Dance_B7", d: 1.13 },
      { n: "Dance_B8", d: 1.17 },
      { n: "Dance_B9", d: 1.13 },
      { n: "Dance_B10", d: 1.17 },
      { n: "Dance_B11", d: 1.13 },
      { n: "Dance_B12", d: 1.17 },
      { n: "Dance_B13", d: 1.13 },
      { n: "Dance_B14", d: 1.17 },
      { n: "Dance_B15", d: 1.13 },
      { n: "Dance_B16", d: 1.17 },
      { n: "Dance_G1", d: 1.13 },
      { n: "Dance_G2", d: 1.17 },
      { n: "Dance_G3", d: 1.13 },
      { n: "Dance_G4", d: 1.17 },
      { n: "Dance_G5", d: 1.13 },
      { n: "Dance_G6", d: 1.17 },
      { n: "Dance_G7", d: 1.13 },
      { n: "Dance_G8", d: 1.17 },
      { n: "Dance_G9", d: 1.13 },
      { n: "Dance_G10", d: 1.17 },
      { n: "Dance_G11", d: 1.13 },
      { n: "Dance_G12", d: 1.17 },
      { n: "Dance_G13", d: 1.13 },
      { n: "Dance_G14", d: 1.17 },
      { n: "Dance_G15", d: 1.13 },
      { n: "Dance_G16", d: 1.17 },
      { n: "dance_loop", d: 1.17 },
    ],
  ],
  [
    "WUZI",
    [
      { n: "CS_Dead_Guy", d: 5.07 },
      { n: "CS_Plyr_pt1", d: 3.77 },
      { n: "CS_Plyr_pt2", d: 9.67 },
      { n: "CS_Wuzi_pt1", d: 3.77 },
      { n: "CS_Wuzi_pt2", d: 9.67 },
      { n: "Walkstart_Idle_01", d: 3.17 },
      { n: "Wuzi_follow", d: 3.0 },
      { n: "Wuzi_Greet_Plyr", d: 4.0 },
      { n: "Wuzi_Greet_Wuzi", d: 4.0 },
      { n: "Wuzi_grnd_chk", d: 4.0 },
      { n: "Wuzi_stand_loop", d: 2.67 },
      { n: "Wuzi_Walk", d: 1.17 },
    ],
  ],
]);

export const isValidAnimateLib = (lib: string) => {
  // return Boolean(samp.callNative('IsValidAnimationLibrary', 's', lib))

  const animLib = animateLib.get(lib);
  if (animLib === undefined) return false;
  return animLib;
};

export const isValidAnimateName = (lib: string, name: string) => {
  const animLib = isValidAnimateLib(lib);
  if (!animLib) return;
  if (name === "null") return true;
  return animLib.some((anim) => anim.n === name);
};

export const getAnimateDurationByLibName = (lib: string, name: string) => {
  const animLib = isValidAnimateLib(lib);
  if (!animLib) return;
  return animLib.find((anim) => anim.n === name)?.d;
};
