export enum PR_EventType {
  INCOMING_PACKET,
  INCOMING_RPC,
  OUTGOING_PACKET,
  OUTGOING_RPC,
  INCOMING_CUSTOM_RPC,

  NUMBER_OF_EVENT_TYPES,
}

export enum PR_ValueType {
  INT8,
  INT16,
  INT32,
  UINT8,
  UINT16,
  UINT32,
  FLOAT,
  BOOL,
  STRING,

  CINT8,
  CINT16,
  CINT32,
  CUINT8,
  CUINT16,
  CUINT32,
  CFLOAT,
  CBOOL,
  CSTRING,

  BITS,
  FLOAT3,
  FLOAT4,
  VECTOR,
  NORM_QUAT,

  STRING8,
  STRING32,

  IGNORE_BITS,
}

export enum PR_PacketPriority {
  SYSTEM,
  HIGH,
  MEDIUM,
  LOW,
}

export enum PR_PacketReliability {
  UNRELIABLE = 6,
  UNRELIABLE_SEQUENCED,
  RELIABLE,
  RELIABLE_ORDERED,
  RELIABLE_SEQUENCED,
}

export enum RakNetNatives {
  SEND_PACKET,
  SEND_RPC,
  EMULATE_INCOMING_PACKET,
  EMULATE_INCOMING_RPC,
  NEW,
  NEW_COPY,
  DELETE,
  RESET,
  RESET_READ_POINTER,
  RESET_WRITE_POINTER,
  IGNORE_BITS,
  SET_WRITE_OFFSET,
  GET_WRITE_OFFSET,
  SET_READ_OFFSET,
  GET_READ_OFFSET,
  GET_NUMBER_OF_BITS_USED,
  GET_NUMBER_OF_BYTES_USED,
  GET_NUMBER_OF_UNREAD_BITS,
  GET_NUMBER_OF_BITS_ALLOCATED,
  WRITE_VALUE,
  READ_VALUE,
}

export enum PacketIdList {
  DRIVER_SYNC = 200,
  RCON_COMMAND = 201,
  AIM_SYNC = 203,
  WEAPONS_UPDATE = 204,
  STATS_UPDATE = 205,
  BULLET_SYNC = 206,
  ONFOOT_SYNC = 207,
  MARKERS_SYNC = 208,
  UNOCCUPIED_SYNC = 209,
  TRAILER_SYNC = 210,
  PASSENGER_SYNC = 211,
  SPECTATING_SYNC = 212,

  // RakNet Internal
  INTERNAL_PING = 6,
  CONNECTED_PONG = 9,
  REQUEST_STATIC_DATA = 10,
  CONNECTION_REQUEST = 11,
  AUTH_KEY = 12,
  RPC_MAPPING = 17,
  DETECT_LOST_CONNECTIONS = 23,
  NEW_INCOMING_CONNECTION = 30,
  NO_FREE_INCOMING_CONNECTIONS = 31,
  DISCONNECTION_NOTIFICATION = 32,
  CONNECTION_LOST = 33,
  CONNECTION_REQUEST_ACCEPTED = 34,
  CONNECTION_ATTEMPT_FAILED = 35,
  CONNECTION_BANNED = 36,
  INVALID_PASSWORD = 37,
  MODIFIED_PACKET = 38,
}

export enum RPCIdList {
  ShowActor = 171,
  HideActor = 172,
  ApplyActorAnimation = 173,
  ClearActorAnimation = 174,
  SetActorFacingAngle = 175,
  SetActorPos = 176,
  SetActorHealth = 178,
  SetPlayerAttachedObject = 113,
  ChatBubble = 59,
  DisableCheckpoint = 37,
  SetRaceCheckpoint = 38,
  DisableRaceCheckpoint = 39,
  SetCheckpoint = 107,
  ShowDialog = 61,
  AddGangZone = 108,
  GangZoneDestroy = 120,
  GangZoneFlash = 121,
  GangZoneStopFlash = 85,
  ShowGameText = 73,
  SetGravity = 146,
  SetMapIcon = 56,
  RemoveMapIcon = 144,
  ShowMenu = 77,
  HideMenu = 78,
  ShowPlayerNameTag = 80,
  CreateObject = 44,
  SetPlayerObjectMaterialText = 84,
  AttachObjectToPlayer = 75,
  AttachCameraToObject = 81,
  EditAttachedObject = 116,
  EditObject = 117,
  EnterEditObject = 27,
  CancelEdit = 28,
  SetObjectPos = 45,
  SetObjectRotation = 46,
  DestroyObject = 47,
  MoveObject = 99,
  StopObject = 122,
  CreatePickup = 95,
  DestroyPickup = 63,
  SetPlayerFacingAngle = 19,
  ServerJoin = 137,
  ServerQuit = 138,
  InitGame = 139,
  UpdateScoresAndPings = 155,
  ClientCheck = 103,
  GameModeRestart = 40,
  ApplyPlayerAnimation = 86,
  ClearPlayerAnimation = 87,
  DeathBroadcast = 166,
  SetPlayerName = 11,
  SetPlayerPos = 12,
  SetPlayerPosFindZ = 13,
  SetPlayerSkillLevel = 34,
  SetPlayerSkin = 153,
  SetPlayerTime = 29,
  SetPlayerSpecialAction = 88,
  SetWeather = 152,
  SetWorldBounds = 17,
  SetPlayerVelocity = 90,
  TogglePlayerControllable = 15,
  TogglePlayerSpectating = 124,
  ToggleClock = 30,
  SetPlayerTeam = 69,
  PlaySound = 16,
  GivePlayerMoney = 18,
  ResetPlayerMoney = 20,
  ResetPlayerWeapons = 21,
  GivePlayerWeapon = 22,
  PlayAudioStream = 41,
  PlayCrimeReport = 112,
  StopAudioStream = 42,
  RemoveBuilding = 43,
  SetPlayerHealth = 14,
  SetPlayerArmour = 66,
  SetWeaponAmmo = 145,
  SetCameraBehind = 162,
  SetArmedWeapon = 67,
  WorldPlayerAdd = 32,
  WorldPlayerRemove = 163,
  InterpolateCamera = 82,
  CreateExplosion = 79,
  SendDeathMessage = 55,
  SendGameTimeUpdate = 60,
  SendClientMessage = 93,
  SetShopName = 33,
  SetPlayerDrunkLevel = 35,
  SetPlayerFightingStyle = 89,
  SetInterior = 156,
  SetPlayerColor = 72,
  ForceClassSelection = 74,
  ToggleWidescreen = 111,
  SetPlayerWantedLevel = 133,
  SetCameraPos = 157,
  SetCameraLookAt = 158,
  SetSpawnInfo = 68,
  RequestClass = 128,
  RequestSpawn = 129,
  SpectatePlayer = 126,
  SpectateVehicle = 127,
  EnableStuntBonus = 104,
  ToggleSelectTextDraw = 83,
  TextDrawSetString = 105,
  ShowTextDraw = 134,
  HideTextDraw = 135,
  PlayerEnterVehicle = 26,
  PlayerExitVehicle = 154,
  RemoveVehicleComponent = 57,
  AttachTrailerToVehicle = 148,
  DetachTrailerFromVehicle = 149,
  LinkVehicleToInterior = 65,
  PutPlayerInVehicle = 70,
  RemovePlayerFromVehicle = 71,
  UpdateVehicleDamageStatus = 106,
  ScmEvent = 96,
  SetVehicleNumberPlate = 123,
  DisableVehicleCollisions = 167,
  SetVehicleHealth = 147,
  SetVehicleVelocity = 91,
  SetVehiclePos = 159,
  SetVehicleZAngle = 160,
  SetVehicleParams = 161,
  SetVehicleParamsEx = 24,
  WorldVehicleAdd = 164,
  WorldVehicleRemove = 165,
  Create3DTextLabel = 36,
  Update3DTextLabel = 58,
  SetWorldTime = 94,
  ToggleCameraTarget = 170,

  // 0.3DL
  SetPlayerVirtualWorld = 48,
  ModelInfo = 179,
  ModelFile = 183,
  SrcFinishedDownloading = 185,
  FinishedDownloading = 184,
  RequestDffFile = 181,
  RequestTxdFile = 182,
}
