export {
  onCheatDetected,
  onCheatWarning,
  onFloodWarning,
  onNOPWarning,
} from "./callbacks";
export { defineNexACConfig } from "./config";
export {
  antiCheatGetAmmoInSlot,
  antiCheatGetAnimationIndex,
  antiCheatGetArmour,
  antiCheatGetEnterVehicle,
  antiCheatGetEnterVehicleSeat,
  antiCheatGetHealth,
  antiCheatGetInterior,
  antiCheatGetLastEnteredVehTime,
  antiCheatGetLastPickup,
  antiCheatGetLastReloadTime,
  antiCheatGetLastShotTime,
  antiCheatGetLastShotWeapon,
  antiCheatGetLastSpawnTime,
  antiCheatGetLastSpecialAction,
  antiCheatGetLastUpdateTime,
  antiCheatGetPos,
  antiCheatGetSpawnPos,
  antiCheatGetSpawnWeapon,
  antiCheatGetSpecialAction,
  antiCheatGetSpeed,
  antiCheatGetVehicleDriver,
  antiCheatGetVehicleHealth,
  antiCheatGetVehicleID,
  antiCheatGetVehicleInterior,
  antiCheatGetVehiclePaintjob,
  antiCheatGetVehiclePos,
  antiCheatGetVehicleSeat,
  antiCheatGetVehicleSpawnPos,
  antiCheatGetVehicleSpawnZAngle,
  antiCheatGetVehicleSpeed,
  antiCheatGetVehicleVelocity,
  antiCheatGetVehicleZAngle,
  antiCheatGetWeapon,
  antiCheatGetWeaponData,
  antiCheatGetWeaponInSlot,
  antiCheatIntEnterExitsIsEnabled,
  antiCheatIsConnected,
  antiCheatIsDead,
  antiCheatIsFrozen,
  antiCheatIsInModShop,
  antiCheatIsInSpectate,
  antiCheatIsKickedWithDesync,
  antiCheatKickWithDesync,
  antiCheatStuntBonusIsEnabled,
  enableAntiCheat,
  enableAntiCheatForPlayer,
  enableAntiNOP,
  enableAntiNOPForPlayer,
  isAntiCheatEnabled,
  isAntiCheatEnabledForPlayer,
  isAntiNOPEnabled,
  isAntiNOPEnabledForPlayer,
} from "./functions";
export { $t } from "./lang/index";
