name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: github.repository == 'dockfries/infernus'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release for Tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
